### ISSUE TITLE
Please reconsider deprecating "assert_equal nil, ..."

### ISSUE THREAD

**Issue by gerbils** [minitest/minitest#1004]
When I test the values in structs and the attributes of classes, I typically don't write an assert for each. Instead I create a hash where the key is the field name and the value is the expected value, and then loop over it.

For example, to test the fields in an order I might write:

~~~ ruby
def check_fields(actual, expected)
  expected.each do |ek, ev|
    assert_equal(ev, actual[ek]), ek)
  end
end

# ....

def test_the_order
  o = Order.most_recent
  check_fields(o, {
    number: 123,
    name: "elmo",
    company:  nil,
    # ...
  })
end
~~~

Fairly recently, Minitest started complaining about the `company: nil` test:

```
DEPRECATED: Use assert_nil if expecting nil from test/nonweb/pip_import_order_test.rb:55. This will fail in Minitest 6.
```

Any chance we could discuss this....?

Dave

**Comment by zenspider** [comment]
2018 is not "fairly recently"... And no, this isn't open for discussion. Thank you for your understanding.

**Comment by gerbils** [comment]
Brutal, Ryan. Brutal :)

@pragdave
