### ISSUE TITLE
Broken Parallelization in 5.25.0

### ISSUE THREAD

**Issue by phil-6** [minitest/minitest#1007]
It seems as though 5.25.0 has broken parallelization.

Minitest::Runnable has
``` ruby
  def self.with_info_handler reporter, handler, &block # :nodoc:
    on_signal ::Minitest.info_signal, handler, &block
  end
```

which is called from ActiveSupport::Testing::Parallelization::Worker
``` ruby
  def perform_job(job)
    klass    = job[0]
    method   = job[1]
    reporter = job[2]

    set_process_title("#{klass}##{method}")

    result = klass.with_info_handler reporter do
      Minitest.run_one_method(klass, method)
    end

    safe_record(reporter, result)
  end
```
which is missing the handler argument.

Full Error
``` 
# Running:

/home/phil/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/minitest-5.25.0/lib/minitest.rb:457:in `with_info_handler': wrong number of arguments (given 1, expected 2) (ArgumentError)
        from /home/phil/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization/worker.rb:49:in `perform_job'
        from /home/phil/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization/worker.rb:38:in `work_from_queue'
        from /home/phil/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization/worker.rb:27:in `block in start'
        from /home/phil/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization/worker.rb:15:in `fork'
        from /home/phil/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization/worker.rb:15:in `start'
        from /home/phil/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization.rb:37:in `block in start'
        from <internal:numeric>:237:in `times'
        from /home/phil/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization.rb:36:in `each'
        from /home/phil/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization.rb:36:in `map'
        from /home/phil/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelization.rb:36:in `start'
        from /home/phil/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/testing/parallelize_executor.rb:19:in `start'
        from /home/phil/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/minitest-5.25.0/lib/minitest.rb:284:in `run'
        from /home/phil/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/minitest-5.25.0/lib/minitest.rb:85:in `block in autorun'
```

First time creating an issue here, so please let me know if I can provide any further info.

**Comment by dentarg** [comment]
Yeah, the `with_info_handler` signature change also breaks https://github.com/jeremyevans/minitest-hooks

```
~/src/minitest-hooks master
$ b e rake
/Users/dentarg/.arm64_rubies/3.2.4/bin/ruby -w spec/all.rb
Run options: --seed 968

# Running:

/Users/dentarg/src/minitest-hooks/lib/minitest/hooks/test.rb:64:in `with_info_handler': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /Users/dentarg/.arm64_rubies/3.2.4/lib/ruby/gems/3.2.0/gems/minitest-5.25.0/lib/minitest.rb:428:in `run'
	from /Users/dentarg/.arm64_rubies/3.2.4/lib/ruby/gems/3.2.0/gems/minitest-5.25.0/lib/minitest.rb:331:in `block in __run'
	from /Users/dentarg/.arm64_rubies/3.2.4/lib/ruby/gems/3.2.0/gems/minitest-5.25.0/lib/minitest.rb:331:in `map'
	from /Users/dentarg/.arm64_rubies/3.2.4/lib/ruby/gems/3.2.0/gems/minitest-5.25.0/lib/minitest.rb:331:in `__run'
	from /Users/dentarg/.arm64_rubies/3.2.4/lib/ruby/gems/3.2.0/gems/minitest-5.25.0/lib/minitest.rb:287:in `run'
	from /Users/dentarg/.arm64_rubies/3.2.4/lib/ruby/gems/3.2.0/gems/minitest-5.25.0/lib/minitest.rb:85:in `block in autorun'
rake aborted!
Command failed with status (1): [/Users/dentarg/.arm64_rubies/3.2.4/bin/ruby -w spec/all.rb]
/Users/dentarg/src/minitest-hooks/Rakefile:15:in `block in <top (required)>'
/Users/dentarg/.arm64_rubies/3.2.4/bin/bundle:25:in `load'
/Users/dentarg/.arm64_rubies/3.2.4/bin/bundle:25:in `<main>'
Tasks: TOP => default => spec
(See full trace by running task with --trace)
```

**Comment by mtasaka** [comment]
Most probably this is due to:

https://github.com/minitest/minitest/commit/8cd3b1c749c778038ead3ddf7894dc19c1fe4797

I am not minitest upstream and I am not sure if `with_info_handler` has any "documentated" API or not.

**Comment by tenderlove** [comment]
Looks like the the call in Rails was to do with supporting minitest-hooks: https://github.com/rails/rails/commit/758ba117a008b6ea2d3b92c53b6a7a8d7ccbca69

I don't see any PR associated, so that's all the context I have.

**Comment by searls** [comment]
Just a note for anyone else who lands here: the impact of updating minitest to this version while running Rails parallelized tests can be pretty expensive, because it will result in the test suite failing during initialization such that all forked processes _just hang forever_. I had a dozen or so Dependabot PRs open and then each time out after 6 hours. As a result, this burned through my monthly GitHub Actions minutes before I even realized I had a build failure

**Comment by zenspider** [comment]
@searls why would they just hang?

**Comment by zenspider** [comment]
@jeremyevans ^^^

**Comment by jeremyevans** [comment]
I released minitest-hooks 1.5.2 with a fix for this today.

**Comment by zenspider** [comment]
activesupport shouldn't be calling `with_info_handler`... nor should minitest-hooks. That is an internal method to minitest and I should be allowed to change it any way I see fit without breaking things... but because of minitest-hooks I can't change the signature now. And since it has wormed its way into activesupport, it is doubly locked in.

I can make what I wanted to do compatible by introducing a civar but it'll be at a performance cost, unfortunately... I really liked that 33% speedup.

**Comment by jeremyevans** [comment]
@zenspider If you provide a supported way to do what minitest-hooks needs, I'll change minitest-hooks to use it.  I only overrode `with_info_handler` because I didn't see another feasible approach.

**Comment by searls** [comment]
> @searls why would they just hang?

Sorry, I didn't have time to investigate exactly, but my guess is that since the raise happened immediately after forking processes that the issue is in the Rails test support code managing those processes

**Comment by jeremyevans** [comment]
In case it helps, the reason `with_info_handler` is overrriden is to avoid running {before/after/around}_all methods if the class has no test methods in it after filtering.

**Comment by zenspider** [comment]
@searls oof. ok. yeah I can see that. prolly needs some timeouts around expecting a response back

**Comment by ioquatix** [comment]
GitHub actions supports job timeouts, which can be useful for preventing cost overruns/extreme usage due to hangs/bugs:

https://github.com/socketry/async/blob/13c0377fe74061809dcbb7496bd09d9102a6f08b/.github/workflows/test.yaml#L49

**Comment by searls** [comment]
@ioquatix lol, thanks that was actually the point of me leaving that comment but I got distracted and forgot to mention! 🤦‍♂️

**Comment by zenspider** [comment]
I believe this is resolved. OP, please close if your issue is handled after updating.

**Comment by phil-6** [comment]
thanks @zenspider! :bow:
