### ISSUE TITLE
assert_equal computes a diff that's unused when the assertion passes

### ISSUE THREAD

**Issue by perryhooker** [minitest/minitest#1018]
`assert_equal` [computes a diff](https://github.com/minitest/minitest/blob/e4417c5b13ab917a60c218700041152136bc07c8/lib/minitest/assertions.rb#L214) of its input arguments. When `assert_equal` passes, the diff is never used. The `diff` operation involves writing the arguments to tempfiles and invoking the system's `diff` command, which is relatively expensive.  In cases where `assert_equal` is called frequently, this can lead to significant runtime cost.

Suggestion: modify `assert_equal` so that the diff is only computed when the assertion fails, e.g.:

```
def assert_equal exp, act, msg = nil
  test_passed = exp == act

  msg = message(msg, E) { diff exp, act } unless test_passed

  assert test_passed, msg

  if exp.nil?
    if Minitest::VERSION >= "6"
      refute_nil exp, "Use assert_nil if expecting nil."
    else
      warn "DEPRECATED: Use assert_nil if expecting nil from #{_where}. This will fail in Minitest 6."
    end
  end

  test_passed
end
```

Happy to put a PR together if this seems like a reasonable change.

**Comment by adam12** [comment]
I feel like I saw @zenspider working on this exact optimization already, so my guess is it's in a private branch on his repo.

**Comment by Cluster444** [comment]
The diff isn't being computed on call, it's lazy evaluated. `message` returns. a proc that wraps the block.

```ruby
    def message msg = nil, ending = nil, &default
      proc {
        msg = msg.call.chomp(".") if Proc === msg
        custom_message = "#{msg}.\n" unless msg.nil? or msg.to_s.empty?
        "#{custom_message}#{default.call}#{ending || "."}"
      }
    end
   ```

**Comment by zenspider** [comment]
Your profile shows the diff method being executed or the line with the message call with diff in the block? Can you share the profile?

**Comment by Cluster444** [comment]
So that looks like PiperTest is monkey patching MT#assert? If that's the case would need to look at that code as well.

`assert_equal > assert > diff`

That's the way that call should go, if it were a failing test, diff isn't being called until inside assert, but that's not MT#assert. My guess is that PiperTest monkey patch is doing something different as it's the one calling `diff`

**Comment by Cluster444** [comment]
Also, I can't find anything named PiperTest, is there a GitHub repo or is that a private code base?

**Comment by Cluster444** [comment]
> Yeah, the PiperTest module is part of our private code base. I _think_ you're correct that we're monkey patching MT#assert - I'll have to check with our testing team. Just curious, what are you seeing that led you to that conclusion?
> 
> Thank you for taking a look. Appreciate the effort.

It was the call stack in the flame graph. Diff was being called from PT#assert instead of MT#assert and MT has a guard clause on block.call, based on your follow up comment it seems that guard clause was dropped in your internal test suite.

```ruby
    def assert test, msg = nil
      self.assertions += 1
      unless test then
        msg ||= "Expected #{mu_pp test} to be truthy."
        msg = msg.call if Proc === msg
        raise Minitest::Assertion, msg
      end
      true
    end
```

With that guard, it's impossible for that diff to get called without a raise happening.

**Comment by zenspider** [comment]
@perryhooker there's prolly very very little legit reason to be overriding `assert`... please consider removing it entirely, renaming it to something more specific, or at least calling up w/ `super` and leaving most/all args alone
