### ISSUE TITLE
Minitest::TestTask by default breaks SimpleCov

### ISSUE THREAD

**Issue by fractaledmind** [minitest/minitest#1020]
I used the `bundle gem <name>` command today to scaffold a new gem. The scaffolded gem had the following in the `Rakefile`

```ruby
require "minitest/test_task"

Minitest::TestTask.create
```

When I added SimpleCov to the gem, it was generating its coverage report _before_ the tests ran, making the coverage report useless. After debugging for a while, I determined that the difference in my gem setup from other gems I maintain and use Minitest and SimpleCov was the `TestTask`. Inspecting the command generated by default, I saw:

```
ruby -Ilib:test:. -w -e 'require "minitest/autorun"; require "test/test_chaotic_job.rb"; require "test/test_helper.rb"' --
```

I suspected that the initial `require "minitest/autorun"` was leading to the broken SimpleCov behavior, so I manually tested running:

```
ruby -Ilib:test:. -w -e 'require "test/test_chaotic_job.rb"' -- 
```

And, indeed, the coverage report was generated after the tests, as desired.

In the end, I found that changing my `Rakefile` to this allowed SimpleCov to function correctly:

```ruby
Minitest::TestTask.create :test do |t|
  t.framework = nil
end

Minitest::TestTask.create :test do |t|
  t.framework = nil
end
```

Not sure the best solution, but wanted to flag for the maintainers that the default implementation of `TestTask`, which is now scaffolded by Bundler for any new gem, is incompatible with SimpleCov.

**Comment by zenspider** [comment]
Here's what hoe does:
```ruby
    desc "Run tests and analyze code coverage"
    task :cov => :isolate do
      cmds = ["add_filter %p" % [cov_filter],
              "enable_coverage :branch",
              "primary_coverage :branch"].join "; "

      test_task.test_prelude =
        %(require "simplecov"; SimpleCov.start { %s }) % [cmds]

      Rake::Task[:test].invoke
    end
```
(the branch coverage part isn't published yet (and really doesn't work well) but the idea is the same)

**Comment by zenspider** [comment]
anything?

**Comment by zenspider** [comment]
no response in 2 weeks. Closing

**Comment by fractaledmind** [comment]
Wait, the "anything?" question was to me? Apologies, I didn't understand it that way at all. I don't know what `hoe` is. And I didn't read a question in that post. What would you like from me?

**Comment by zenspider** [comment]
> There is nothing inherently wrong with Minitest: It merely knows nothing about your test helper. I have written a blog post where I describe my findings and provide a solution to your issue:
> 
> https://intech.ee/articles/fixing-low-code-coverage-when-using-test-helper-with-minitest-simplecov-and-rake.html

Thanks for the writeup! Generally, I advise that all test files require their test helper so that you can run any individual test directly with `ruby -Ilib:test test/path_to_test.rb`.

**Comment by artur-intech** [comment]
@zenspider Thank you for Minitest!

The issue is not about executing a single test file (testcase); I personally use `ruby -I test -r test_helper test/unit/some_test.rb` since I find typing `require "test_helper"` in every file too tedious. It is about running all the tests with SimpleCov using `rake test` task.
