### ISSUE TITLE
Don't use at_exit{}, use END{}

### ISSUE THREAD

**Issue by hakanai** [minitest/minitest#143]
I had an issue where JRuby wasn't running at_exit: https://jira.codehaus.org/browse/JRUBY-6765

They seem to be strongly recommending "not using at_exit for this", but it was MiniTest making the call.

Can you see any reason why MiniTest can't use END instead?

**Comment by ctrochalakis** [comment]
I am having the same problem with @ioquatix. Minitest gets in the way of  testing processes and exit codes.

**Comment by ioquatix** [comment]
I made a PR to fix this but it wasn't accepted because they felt the existing behaviour was okay. I moved to RSpec and have never looked back. RSpec 3 is awesome and doesn't have any issues like this.
