### ISSUE TITLE
Can you mock a class method with MiniTest?

### ISSUE THREAD

**Issue by matthodan** [minitest/minitest#216]
How would I test if the class method `::bar` of `Foo` is being called?  Consider the following example:

``` ruby
# Code
class Alpha
  def process
    Foo.bar
    return nil
  end
end

# Spec
let(:alpha) { Alpha.new }
let(:klass) { MiniTest::Mock.new }

subject { alpha.process }

it "calls Foo::bar" do
  klass.expect(:bar, 'mock-response')
  Foo = klass
  subject 
  klass.verify
end
```

Unfortunately, this approach throws a "class already defined" warning if `Foo` has already been defined, which will usually be the case.

**Comment by leckylao** [comment]
Thanks @willnet for the solution, that's very helpful. But to better understand it, I have to dig into the source to find out the tricky part :call though https://github.com/seattlerb/minitest/blob/master/lib/minitest/mock.rb#L207

I think the use of the :call should be documented somehow

**Comment by jvalanen** [comment]
I vote for documenting ```.expect :call``` too! 
Or is there something available?

**Comment by ktec** [comment]
@zenspider Obviously the decision to deliberately obscure functionality is based on some wisdom, so it might be worth spreading the basis of those ideas to these folks - admittedly their "expressions" are somewhat inappropriate, but I'm sure its out of frustration and a lack of understanding than anything else...

**Comment by zenspider** [comment]
I have no idea what you three are going on about. First, this ticket has been _closed_ *by the OP* for over 2 years. Second, it _is documented_.

https://github.com/seattlerb/minitest/blob/master/lib/minitest/mock.rb#L177

@ktec I'm not "deliberately obscuring" anything. Drop your attitude.

**Comment by zenspider** [comment]
Ya know what? There's no reason for this "dialog" to continue. If you have an issue, open a new one rather than piggy backing on something that's been closed for over 2 years. Locking.
