### ISSUE TITLE
SIGINFO question

### ISSUE THREAD

**Issue by bhenderson** [minitest/minitest#304]
INFO trap is not working on my box (Ubuntu 13.04)

I know almost nothing about this, but after cursory investigation (1 article) I don't think INFO is supported on linux.

Couple of options:

Change it to SIGUSR1, or support both?

On a mac, INFO maps to signal 29.
On linux, 29 maps to POLL. Not sure if you want to do something like

``` ruby
sig = Signal.list.invert[29]
trap(sig)
```

to support any arch that has 29?

I don't know how good it is to trap QUIT, but it's nice that it maps to ctrl-\

thanks,

**Comment by nate** [comment]
Sorry about resurrecting an old issue, but I'd love it if the signal handler for this was configurable. I'm on centos and the INFO signal doesn't work. I've monkey-patched it to use USR1 and I'm sending the signal from a separate terminal and it works fine. It's unfortunate there's no shortcut to the signal like ^T, but it's better than not having the functionality at all.
