### ISSUE TITLE
assert_difference

### ISSUE THREAD

**Issue by ream88** [minitest/minitest#41]
Is there any reason why `assert_difference` isn't implemented in minitest?

**Comment by reggieb** [comment]
You can add assert_difference to an app like this:

Add the gem 'activesupport' to your environment. For example, by adding this to your Gemfile:

    gem 'activesupport'

Then in your test_helper, add this:

    class Minitest::Test
      require 'active_support/testing/assertions'
      include ActiveSupport::Testing::Assertions
    end

**Comment by manuelmeurer** [comment]
Thanks @reggieb, that works nicely! :+1:
