### ISSUE TITLE
how to get --verbose for skipped tests

### ISSUE THREAD

**Issue by nvoynov** [minitest/minitest#463]
Hello,

I have a lot of tests by Minitest. How can I find the skipped tests? I try add --verbose option to rake command, but it does not have any effect. I see the same output in both command variants

rake task:

```
Rake::TestTask.new do |t|
  t.pattern = 'spec/unit/**/*_spec.rb'
  t.verbose = true
end
```

commands:

```
$ rake test
$ rake test --verbose
```

output:

```
128 runs, 198 assertions, 0 failures, 0 errors, 1 skips
You have skipped tests. Run with --verbose for details.
```

**Comment by odigity** [comment]
This doesn't seem to work.

I've got a StackOverflow question about it, but it has received no attention:

http://stackoverflow.com/questions/32956801/what-is-the-point-of-setting-testopts-v-with-rake-test

**Comment by utilum** [comment]
What is the question?

**Comment by odigity** [comment]
Well, I explained it in the SO question (which I linked to above), so didn't feel it was worth repeating.

But I have since opened a more general issue for the problem:

https://github.com/seattlerb/minitest/issues/583
