### ISSUE TITLE
Include the public cert?...

### ISSUE THREAD

**Issue by ToadJamb** [minitest/minitest#469]
```
The gem minitest-5.4.2 can't be installed because the security policy didn't allow it, with the message: root cert /CN=ryand-ruby/DC=zenspider/DC=com is not trusted
```

When installing minitest using high security, I am notified that version 5.4.2 cannot be installed because of an untrusted cert, but can find no trace of the public cert. Did I miss it?

**Comment by heph** [comment]
Any chance we could get that hosted somewhere with a valid HTTPS cert so we can have some trust in the chain?

**Comment by zenspider** [comment]
> On Jun 23, 2015, at 11:29, Steve Adams <notifications@github.com> wrote:
> 
> Any chance we could get that hosted somewhere with a valid HTTPS cert so we can have some trust in the chain?

Not if I have to pay for it, no. I use an SSL cert from cacert.org. Their root cert is at:

https://www.cacert.org/index.php?id=3

**Comment by zenspider** [comment]
(I've since switched to letsencrypt so this should be better)
