### ISSUE TITLE
NoMethodError for BenchSpec.bench_range

### ISSUE THREAD

**Issue by rickhull** [minitest/minitest#477]
minimal test case here: https://gist.github.com/rickhull/cb47779ef9e48a7d5189

This case works as expected in Minitest 4.x

Under 5.x, I get the NoMethodError:

```
test.rb:5:in `block in <main>': undefined method `bench_range' for #<Class:0x000000027d4d60> (NoMethodError)
```

Ruby version 2.1.4 (issue manifests for all Rubies > 2 that I have tried)

**Comment by aj0strow** [comment]
@zenspider what's the reason behind excluding the methods? I feel `require "minitest/benchmark"` is a fairly explicit opt-in

**Comment by zenspider** [comment]
Minitest is not excluding anything. You're picking the wrong superclass if you don't name the describe correctly. See https://github.com/seattlerb/minitest/blob/master/lib/minitest/spec.rb#L119-L157

**Comment by aj0strow** [comment]
@zenspider i mean benchmark methods in all specs, for ex losing the regex restriction at [line 424](https://github.com/seattlerb/minitest/blob/master/lib/minitest/benchmark.rb#L424
)

```ruby
# minitest/benchmark.rb

  Minitest::Spec.register_spec_type(/.*/, Minitest::BenchSpec)   # not /Bench(mark)$/
```

I thought `require 'minitest/benchmark'` would mixin benchmark methods (module style) for me. I know it's a small thing, but tripped me up is all.

**Comment by zenspider** [comment]
Don't mix benchmark tests and regular tests. Not a good idea.
