### ISSUE TITLE
Interest in assert_raises_with_message?

### ISSUE THREAD

**Issue by fny** [minitest/minitest#530]
`TestUnit` provides an [`assert_raise_with_message` assertion](http://ruby-doc.org/stdlib-2.1.0/libdoc/test/unit/rdoc/Test/Unit/Assertions.html#method-i-assert_raise_with_message).  Is `assert_raises_with_message` considered in scope for Minitest?

Right now it's not terribly painful take care manually, but it definitely becomes a bit cumbersome when testing a lot of exceptions:

``` ruby
 err = assert_raises(NameError) { blah }
 assert_equal "NameError: undefined local variable or method `blah'", err.message
```

Rough implementation:

``` ruby
def assert_raises_with_message(exception, err_message, msg = nil)
  err = assert_raises(exception, msg) { yield }
  if err_message.is_a?(Regexp)
    assert_matches err_message, err.message
  else
    assert_equal err_message, err.message
  end  
end
```

**Comment by zenspider** [comment]
Not sure about implementation, but yes, interested.

**Comment by fny** [comment]
In the tests, there's a check in the teardown that ensures only one assertion is fired. It seems to make sense for two assertions (assert_raises then assert_equal/assert_matches) to be called in this case. Thoughts?

```ruby
def assert_raises_with_message(exception, expected_msg, msg = nil)
  case expected_msg
  when String
    assert = :assert_equal
  when Regexp
    assert = :assert_match
  else
    raise TypeError, "Expected #{mu_pp(expected_msg)} to be a kind of String or Regexp, not #{expected_msg.class}"
  end
  ex = assert_raises(exception, msg) { yield }
  msg = message(msg, "") {"Expected Exception (#{exception}) to be raised, but the message doesn't match"}

  if assert == :assert_equal
    assert_equal(expected_msg, ex.message, msg)
  else
    msg = message(msg) { "Expected #{mu_pp(expected_msg)} to match #{mu_pp(ex.message)}" }
    assert_matches expected_msg, ex.message, msg
  end
  ex
end
```

**Comment by zenspider** [comment]
I'm really not fond of that level of complexity. Let me think about an alternative.

**Comment by AlexWayfer** [comment]
I'm very interested in this assertion.

**Comment by knightq** [comment]
Me too!

**Comment by zenspider** [comment]
I'm not interested in this at this point.

I have modified assert_raises to return the exception
