### ISSUE TITLE
Set expectation on call, but not on return value

### ISSUE THREAD

**Issue by zamith** [minitest/minitest#540]
It is currently not possible to set an expectation in which we do not care about the return value, only that the method is called.

Is this something you did not include for any particular reason? Are you open to it?

I'd love to give it a try, if you are interested.

**Comment by zenspider** [comment]
Is `nil` a bad default in this case? I guess I don't understand the scenario because I don't think this way. If you want to take a whack at it, go for it.

**Comment by zamith** [comment]
`nil` is fine, but since it is the middle argument, we have to set it explicitly. I think code explains this better:

```ruby
mock = Minitest::Mock.new
mock.expect(:method, nil, [:argument1, :argument2])
```

And I would like to have:

```ruby
mock = Minitest::Mock.new
mock.expect(:method, [:argument1, :argument2])
```

Where the return was inferred. But this is hard (if not impossible) to do without changing the arguments to `expect` to either take the return value at the last position, or to use kwargs.

However, this is not a major issue for me, and it seems not to be an issue for you at all, so I'm not sure if it is worthy of the time.

**Comment by zenspider** [comment]
Your call. Please close if you think this should be.

P.S. What do you think about extracting mocks into its own gem that you can evolve at your own speed?

**Comment by zenspider** [comment]
@zamith *ping* I'm seriously considering making minitest-mock as a separate gem and making you owner. Thoughts?

**Comment by zamith** [comment]
That's ok with me. I'll probably ping you now and then to make sure we're
still on the minitest philosophy path, if that's ok.

Also, how do you plan to make the migration happen? Have minitest require
it by default for a while and deprecated it's usage like that?

**Comment by zenspider** [comment]
I think I'm gonna close this ticket. The API change suggested isn't really possible in a backwards compatible way. Sorry this sat for so long.
