### ISSUE TITLE
Quiet Minitest::Benchmark output

### ISSUE THREAD

**Issue by ghost** [minitest/minitest#616]
I've incorporated Minitest::Benchmark into my the primary rake :test task that runs all tests (coverage, feature, unit, and performance). This get's run primarily for CI purposes, but occasionally manually in development. When I do run it for development purposes I like to keep the output as clean as possible (just a bunch of ... success dots FF failures etc.) and Minitest::Benchmark was giving output every time.

I dove into the code and saw I could overwrite the reporter with IO to /dev/null. Here is that [nasty hack](https://github.com/wurde/canvas/blob/a602e7a318ea11bfc9c37d65f1f2d995ecb9ba6c/lib/canvas/ruby/canvas_test_performance.rb#L284-L288) to redirect output to /dev/null.

**Comment by PuZZleDucK** [comment]
I've failed in a naive attempt to add this to MiniTest... however there was a suggestion that this might be a good candidate for a reporter plugin.

**Comment by PuZZleDucK** [comment]
I've not been able to work out how to even run a plugin... far from writing one. I'm afraid this one is over my head.

**Comment by utilum** [comment]
minitest-reporters ?
