### ISSUE TITLE
Make exception available in after_run

### ISSUE THREAD

**Issue by pschambacher** [minitest/minitest#618]
There's no way to know in after_run what exception stopped the run.
Could you please me it available via a parameter or set Minitest.exception?

**Comment by zenspider** [comment]
Sorry, but I don't understand. What problem are you seeing and how do you reproduce it?

**Comment by pschambacher** [comment]
I would like to prevent some post-treatment information (like code coverage for instance) when Minitest was interrupted by the user.
So this would be

```ruby
Minitest.after_run do
  do_some_stuff unless xxx.is_a?(Interrupt)
```

My problem is that there's no access to the `Interrupt` error in the after_run hook to know if it ended normally or via `Ctrl-C`.

**Comment by zenspider** [comment]
I'm poking at this. Not sure if I'm going to have that info when we get there... what about NOT running the blocks at all if there was an Interrupt?

**Comment by pschambacher** [comment]
That would work for my use case for sure.

**Comment by blowmage** [comment]
In my main project we perform a bunch of setup on external services, and then we tear that down in the `after_run`. We want our teardown to run every time, even if we interrupt.

**Comment by zenspider** [comment]
I should also point out... You can always interrupt the post processing with an extra `^c`...

**Comment by zenspider** [comment]
I think in this case I'm going to opt out of this one... it's a mixed bag what the behavior should be, a second ^c will always work fine, and the information is actually not easily available the way interrupts and other passthrough exceptions are handled.
