### ISSUE TITLE
Clarification on StatisticsReporter's Public API

### ISSUE THREAD

**Issue by sshaw** [minitest/minitest#631]
[The docs for `StatisticsReporter`](http://docs.seattlerb.org/minitest/Minitest/StatisticsReporter.html) say:

> ... If you want to create an entirely different type of output (eg, CI, HTML, etc), this is the place to start.

This indicates that it is part of the public API but the accessors one needs to use in order to create an entirely different type of output [have `stopdoc` directives](https://github.com/seattlerb/minitest/blob/4e146b1515b19a5c474e39c174b037510f6dbc6e/lib/minitest.rb#L497-L506).  Is this intentional or are these accessors safe to use in subclasses?

**Comment by zenspider** [comment]
Seems counterintuitive, doesn't it? Looking...

**Comment by zenspider** [comment]
Nope. Makes no sense. I was probably being lazy. Consider them public and feel free to throw me a PR with doco on them.

**Comment by sshaw** [comment]
>  Consider them public and feel free to throw me a PR with doco on them.

Will do.

**Comment by zenspider** [comment]
This seems hondled
