### ISSUE TITLE
LICENSE.md?

### ISSUE THREAD

**Issue by nateberkopec** [minitest/minitest#654]
Any opposition to moving the license to a separate LICENSE.md file? It's becoming more of a convention - I look for it in repos first rather than looking in the README. Github also gives you a neato badge: 
<img width="453" alt="screen shot 2016-10-28 at 5 30 14 pm" src="https://cloud.githubusercontent.com/assets/845662/19825263/33de3ba8-9d34-11e6-81f7-d6aa2b1972d4.png">

**Comment by predatorian3** [comment]
https://github.com/seattlerb/minitest/pull/786/files

**Comment by zenspider** [comment]
meh
