### ISSUE TITLE
sort.shuffle vs sort.sort_by { rand max}?

### ISSUE THREAD

**Issue by aquach** [minitest/minitest#680]
Hiya,

I just hit an issue where a coworker and I had different method orderings even with the same seed. We tracked it down to a an issue with `sort.sort_by { rand max }` in `runnable_methods` where our method orderings were diverging. Switching to `sort.shuffle` gave us both the same results, so we stopped the investigation there.

If I had to guess, `sort_by` is breaking ties since `rand max` is not guaranteed to return unique values, and the tiebreaking may be happening using factors that might be breaking out of the randomness sandbox (ie, C pointer comparisons, etc). `shuffle` seems to be a better fit?

**Comment by nateberkopec** [comment]
That's weird. I recall having a conversation with @zenspider about changing it to shuffle for perf reasons, but I think the reason it was originally written as sort_by rand max was to prevent the exact issue you're describing. Your guess as to why this is happening is good though.

Which Ruby version are you using?

**Comment by aquach** [comment]
2.2.2p95.

**Comment by zenspider** [comment]
I think the only way I can see it coming up with something different would be architectural differences? Are these different types of machines or modes that ruby was built in?

**Comment by aquach** [comment]
My bad, I could've provided this info earlier. I'm on Ubuntu 14.04 using Ruby built from rbenv. My coworker's on Mac, also using Ruby built from rbenv. FWIW, our CircleCI tests using 14.04 got the same randomization order as my computer, so it seems like an OS thing. We didn't try to isolate it since we found an adequate solution.

**Comment by zenspider** [comment]
If I do `methods.shuffle` I only have to fix a single test's expected order. If I do `methods.sort.shuffle` a whole bunch more fail. No biggie either way, but maybe the second version is a bit more version proof? I dunno. I'm prolly gonna throw the first one in for now and see how it goes.

**Comment by zenspider** [comment]
I just made both class level and test level use plain `shuffle`
