### ISSUE TITLE
infect_an_assertion with namespaced constant overwrites wrong matcher

### ISSUE THREAD

**Issue by apotonick** [minitest/minitest#686]
The problem is when you `infect_an_assertion` on a namespaced constant with the same name that has been injected before.

```ruby
module MiniTest::Assertions
  def for_a(text, subject)
    raise "I am never called because I get overridden"
  end

  def for_b(text, subject)
    text.must_equal "from B"
  end
end

module My
  class A
  end

  class B
  end
end

My::A.infect_an_assertion :for_a, :must_inspect # this one gets overridden by the next line!
My::B.infect_an_assertion :for_b, :must_inspect
```

When using the matchers, the `for_a` method is never called, it's always `for_b`, even on `My::A` instances.

```ruby
require "test_helper"

class BlaTest < Minitest::Spec
  it do
    My::A.new.must_inspect "from A" # FAILS: Expected: "from B"
  end

  it do
    My::B.new.must_inspect "from B" # Passes!
  end
end
```

This only happens with namespaced constants. 5.10.1

**Comment by zenspider** [comment]
Correct. This is what happens currently.

What you haven't stated (and I'm not trusting my intuition on this one yet) is what you expect to happen. Attached to that I'd like to understand the _why_ of it. The source of my confusion centers around:

https://github.com/seattlerb/minitest/blob/master/lib/minitest/spec.rb#L30

and

https://github.com/seattlerb/minitest/blob/master/lib/minitest/spec.rb#L19-L23

versus your use of free floating classes. Ah. and toss in:

https://github.com/seattlerb/minitest/blob/master/lib/minitest/spec.rb#L304-L306

for good measure. That's the real source for my confusion. The context needs to come from somewhere in order to call through and bind to the real assertion code.

**Comment by apotonick** [comment]
Thanks Ryan for coming back so promptly! Indeed an interesting problem.

What I don't understand in the first place why we insert code into this global namespace `Minitest::Expectation`. Intuitively, I'd probably do something along this (untested):

```ruby
def self.infect_an_assertion(target_constant, implementation, name)
  method = make_this_a_matcher_somehow(implementation, name)
  target_constant.class_eval do # only magic part!
    def name(*args)
     method.(*args)
    end
  end 
end
```

By extending the target constant, you don't need to save it and there's less state to float around. But I understand this is an architectural thing now.

**Comment by zenspider** [comment]
sorry for this sitting and going stale...

I think, given that the global expectation pattern is deprecated in favor of `_(value).must_expectation ...` that this issue no longer fits.

Given the contemporary version of `_(My::A.new).must_inspect "from A"`, I expect it to fail with the above code. I don't think it makes too much sense for customizable expectations based on receiver class... dor do I think it makes much sense to have `infect` inject methods into different classes... The whole `_(...)` movement is to go away from test methods being injected into implementation classes at this point.

As such, I think I should close this. 

NOTE: I would be open to arguments towards a different sort of system... some sort of "multi-method" type of dispatcher or some-such... but with the current architecture, that would have to wait for a major rev and I'm not currently convinced it would be worth the effort/complexity (I think debugging rspec is one of the hardest things in the world and I deliberately designed minitest/spec to be vastly simpler so failures happen as close to the real thing as possible).
