### ISSUE TITLE
rr from Benchmark#fit_linear is not that useful

### ISSUE THREAD

**Issue by rickhull** [minitest/minitest#719]
See PR #718 for a demonstration.  In a nutshell: 

The `r^2` value for `fit_linear` has trouble distinguishing `f(x) = mx + b` from `f(x) = x^2` or even `f(x) = x^3`.  For `xs = [1, 10, 100, 1000]`, the `r^2` value for `f(x) = x^2` and `x^3` is over 0.99.

## Why doesn't a linear r^2 distinguish from x^2 or x^3 data?

I am not a statistician but more of an inquisitive novice.  From my brief research, and thanks to the [comments in the minitest code](/seattlerb/minitest/tree/master/lib/minitest/benchmark.rb#L220), it looks to me like the r^2 for a linear fit ([coefficient of determination](https://en.wikipedia.org/wiki/Coefficient_of_determination)) is [deliberately crafted](https://en.wikipedia.org/wiki/Linear_least_squares_\(mathematics\)) to distinguish from (noisy) constant data.  It's a measurement of the extent to which a **linear f(x) predictor** has smaller error than a **constant f(x) predictor**.  In the case of `f(x) = x^2`, the constant error is humongous and swamps the laughable linear fit's no doubt considerable error. 

## What can be done?

I suggest that for asserting an O(n) type behavior, the xs and ys are fit against a multitude of fit functions.  The one with the greatest r2 is chosen.  The assert should match the greatest r2 choice.  I haven't done the math, but this should be a robust approach.

## Notes

* I plan to update this comment with more links and info as they become available (2017-10-31)

**Comment by rickhull** [comment]
Implemented `Fit.best` here as an example: https://github.com/rickhull/compsci/blob/master/lib/compsci/fit.rb#L22

It is not robust for detecting actually constant data, demonstrated (somewhat) here: https://github.com/rickhull/compsci/blob/master/test/bench/complete_tree.rb

Here is some sample output from repeated runs:

```
vagrant@contrib-jessie:~/git/compsci (master)$ ruby -Ilib test/bench/complete_tree.rb
CompleteTree(10) push: 0.00000079
CompleteTree(100) push: 0.00000061
CompleteTree(1000) push: 0.00000062
CompleteTree(10000) push: 0.00000059
CompleteTree(100000) push: 0.00000058
best fit: power (0.665); a = 0.000001, b = -0.028191

vagrant@contrib-jessie:~/git/compsci (master)$ ruby -Ilib test/bench/complete_tree.rb
CompleteTree(10) push: 0.00000059
CompleteTree(100) push: 0.00000068
CompleteTree(1000) push: 0.00000068
CompleteTree(10000) push: 0.00000060
CompleteTree(100000) push: 0.00000058
best fit: exponential (0.321); a = 0.000001, b = -0.000001

vagrant@contrib-jessie:~/git/compsci (master)$ ruby -Ilib test/bench/complete_tree.rb
CompleteTree(10) push: 0.00000059
CompleteTree(100) push: 0.00000063
CompleteTree(1000) push: 0.00000059
CompleteTree(10000) push: 0.00000066
CompleteTree(100000) push: 0.00000058
best fit: linear (0.149); a = 0.000001, b = -0.000000

vagrant@contrib-jessie:~/git/compsci (master)$ ruby -Ilib test/bench/complete_tree.rb
CompleteTree(10) push: 0.00000069
CompleteTree(100) push: 0.00000065
CompleteTree(1000) push: 0.00000064
CompleteTree(10000) push: 0.00000065
CompleteTree(100000) push: 0.00000082
best fit: exponential (0.907); a = 0.000001, b = 0.000002

vagrant@contrib-jessie:~/git/compsci (master)$ ruby -Ilib test/bench/complete_tree.rb
CompleteTree(10) push: 0.00000063
CompleteTree(100) push: 0.00000057
CompleteTree(1000) push: 0.00000059
CompleteTree(10000) push: 0.00000064
CompleteTree(100000) push: 0.00000065
best fit: linear (0.308); a = 0.000001, b = 0.000000

vagrant@contrib-jessie:~/git/compsci (master)$ ruby -Ilib test/bench/complete_tree.rb
CompleteTree(10) push: 0.00000061
CompleteTree(100) push: 0.00000063
CompleteTree(1000) push: 0.00000068
CompleteTree(10000) push: 0.00000065
CompleteTree(100000) push: 0.00000058
best fit: linear (0.511); a = 0.000001, b = -0.000000
```

**Comment by zenspider** [comment]
Agreed... for reasons stated in the referenced PR... still closing.... 

BUT! feel free to reopen if you think this is worth hashing out further... esp if you can get a statistician to weigh in on the correct approach.

I suspect the current approach works fine in most cases where there's enough data to distinguish between squared and cubed... I suspect there might even be a "meta-fitness" heuristic/alg that could test whether there's enough data for a proper fit.
