### ISSUE TITLE
--show-skip option?

### ISSUE THREAD

**Issue by MSP-Greg** [minitest/minitest#767]
One may not want to use `--verbose`, but one may want to see skips in the summary.

Ruby Core has the option in their test suite.  Would a PR for this be ok?

Thanks, Greg

**Comment by utilum** [comment]
Skips are printed in the summary by default.

```
require 'minitest/autorun'

class TestMe < Minitest::Test
  def test_the_truth
    assert true
  end

  def test_the_skip
    skip
  end
end
```

```
$ ruby -w test_skips_in_summary.rb 
Run options: --seed 30631

# Running:

.S

Finished in 0.002113s, 946.5708 runs/s, 473.2854 assertions/s.

2 runs, 1 assertions, 0 failures, 0 errors, 1 skips

You have skipped tests. Run with --verbose for details.
```

What do you mean by
> Ruby Core

?

**Comment by MSP-Greg** [comment]
@utilum

Re `--show-skip`, from the method in `Minitest::SummaryReporter`,
https://github.com/seattlerb/minitest/blob/e6bc4485730403faff6966c1671cf5de72b2d233/lib/minitest.rb#L727-L736


Update the code to allow the following to work - change:

```ruby
filtered_results.reject!(&:skipped?) unless options[:verbose]
```

```ruby
filtered_results.reject!(&:skipped?) unless options[:verbose] || options[:show_skip]
```

By Ruby Core, I mean [ruby/ruby](https://github.com/ruby/ruby)

Thanks, Greg

**Comment by utilum** [comment]
I don't see anything like what you suggest in ruby repository:

https://github.com/ruby/ruby/search?q=show_skip&unscoped_q=show_skip

You mean that a `--show-skipped` option is available to your tests elsewhere?

In fact, when I search all Github repositories in Ruby for `:show_skip` the only results seem to be your own repositories : https://github.com/search?q=%3Ashow_skip&type=Code&l=Ruby .So you have your custom reporter working? Cool! Of course you can also filter the results in the shell.

All this said, you are making a feature request. Let's see what the code owner thinks.

**Comment by MSP-Greg** [comment]
> I don't see anything like what you suggest in ruby repository:

See [test/lib/test/unit.rb](
https://github.com/ruby/ruby/blob/a03ea378e79048ac188c8e4211ed2305e4643558/test/lib/test/unit.rb)#L577-L579

Greg

**Comment by utilum** [comment]
Granted, it exists in the legacy `Test::Unit`.

**Comment by MSP-Greg** [comment]
Which is used by (and available in) their main MRI test suite `test-all`...

**Comment by MSP-Greg** [comment]
Working with Ruby testing and testing in several other repos, I often prefer to not use `--verbose`, but I still want the display of skipped tests.

The option to have every test that doesn't pass shown at the end of the output can be helpful...

**Comment by utilum** [comment]
I think you can have what you describe with minitest-reporters: https://github.com/kern/minitest-reporters

**Comment by MSP-Greg** [comment]
@utilum

Thank you for the link.  This is concerning CI testing, and adding another gem just for the feature seems wasteful.  I could also write a simple patch for it.

I was asking because I thought it would be a helpful feature to have included.  Often, skips are used for engine or platform dependent features (ruby, jruby, windows), and those skips may be helpful to see without using `--verbose`.

**Comment by MSP-Greg** [comment]
@zenspider

Any thoughts?  For large test suites (like Ruby test-all), I hate `--verbose` output (prefer the dots), so having a `--show-skip` option I found helpful, especially when working with cross-platform testing.

If you're not interested, feel free to close...

**Comment by MSP-Greg** [comment]
@zenspider

I'm testing locally in Puma, and came across this again today.  I just noticed the 'self-assigned'.  Can I help?

I mentioned cross-platform testing, and one reason seeing the skips is helpful is that (when done properly) they don't skip based on OS, but on feature.  For instance, with Puma, tests skip for lack of fork, UNIXSockets, unavailable signals. etc.  But, we have to have verbose on to see the info...

Thanks, Greg

**Comment by zenspider** [comment]
@MSP-Greg yeah, I'm down.

**Comment by zenspider** [comment]
@MSP-Greg you wanna take a whack?

**Comment by MSP-Greg** [comment]
@zenspider

Sure.  It will not happen tomorrow.

Screwing around with UNIXSockets, inherited fd's, and systemd.  Which would be fine, except I'm a Windows guy...

**Comment by zenspider** [comment]
Obviously there's no rush given how lax I've been on this.

If you're a windows guy, we should probably talk. I could use some help for an _elegant_ cross-platform way to make minitest-server work.

**Comment by MSP-Greg** [comment]
@zenspider

Sorry for the late response...

I've got a few things to work on, but I noticed the above.  Windows doesn't have UNIXSockets, and it appears that minitest-server is using them.  If it can be changed to TCP (or maybe UDP?), it will probably work?  I know that all the DRb tests do pass on both Windows mingw and mswin.

**Comment by zenspider** [comment]
Added
