### ISSUE TITLE
Some controller tests fails when i run all them, but failed tests pass if run each one

### ISSUE THREAD

**Issue by sdilshod** [minitest/minitest#822]
Hello to all!

Ruby version - 2.3.4p301
Rails version - 5.0.7.2
Gemfile screenshot - http://i.imgur.com/tzQ2NdR.png
part of test_helper.rb - http://i.imgur.com/WxYEhux.png
failed test when run all of them together - http://i.imgur.com/PgjHnu5.png
If i run those failed tests all of them pass - http://i.imgur.com/6HCyHR7.png

I don't any idea how to fix this. Is there any way to fix this?

thanks in advance ...

**Comment by blowmage** [comment]
Hi, this is a question better suited to StackOverflow than on this GitHub repo. But i'll take a swing at answering it for you here.

The most likely culprit for tests failing when loaded and running together is that the tests are overriding some shared value. Each test assumes the value it sets will remain, but the value is overridden by another test and causes the test to fail. To illustrate this, let's assume the following 3 tests:

`foo_test.rb`

```ruby
require "minitest/autorun"

$THING = :foo
class FooTest < Minitest::Test
  def test_foo
    assert_equal :foo, $THING
  end
end
```

`bar_test.rb`

```ruby
require "minitest/autorun"

$THING = :bar
class BarTest < Minitest::Test
  def test_bar
    assert_equal :bar, $THING
  end
end
```

`baz_test.rb`

```ruby
require "minitest/autorun"

$THING = :baz
class BazTest < Minitest::Test
  def test_baz
    assert_equal :baz, $THING
  end
end
```

When they are run separately they all pass just fine.

```
$ ruby foo_test.rb 
Run options: --seed 6486

# Running:

.

Finished in 0.000821s, 1218.0268 runs/s, 1218.0268 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
$ ruby bar_test.rb 
Run options: --seed 2000

# Running:

.

Finished in 0.000794s, 1259.4459 runs/s, 1259.4459 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
$ ruby baz_test.rb 
Run options: --seed 17309

# Running:

.

Finished in 0.001203s, 831.2552 runs/s, 831.2552 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

But when they are all run together, they each overwrite `$THING`, and only the last test loaded passes.

```
$ ruby -I. -e "require 'foo_test'; require 'bar_test'; require 'baz_test'"
Run options: --seed 47651

# Running:

FF.

Finished in 0.001778s, 1687.2891 runs/s, 1687.2891 assertions/s.

 1) Failure:
FooTest#test_foo [./foo_test.rb:6]:
Expected: :foo
 Actual: :baz

 2) Failure:
BarTest#test_bar [./bar_test.rb:6]:
Expected: :bar
 Actual: :baz

3 runs, 3 assertions, 2 failures, 0 errors, 0 skips
```

**Comment by sdilshod** [comment]
Hi @blowmage !

Thank you very much, I will look this way and check my tests!

**Comment by zenspider** [comment]
First, please never submit graphics when you can submit text. We deal with text on a daily basis... we're good at it. (tho the arrows are nice! they're not necessary)

Steps to diagnose:

1. Add and install `minitest-sprint` and `minitest-bisect`.
2. using `minitest` as your test runner get the whole suite to fail:

```
$ minitest test/{unit,functional,whatever}
```

This will output the run and hopefully fail. Grab the seed that was used in that run.

3. Rerun using `minitest-bisect` with all the same args and add `--seed ###`:

```
$ minitest_bisect --seed 42 test/{unit,functional,whatever}
```

This will go through several steps. First, rerun the whole thing trying to see that it reproducibly fails. Next, it'll rerun just the failures to make sure that they do not fail (this doesn't always hit, depending on how they're infecting each other). Finally, it'll go through a series of reductions to get the culprits down to a minimal reproduction. Often, this is just 2 tests.

4. Look at the N tests left. This is the hard part. Assuming two, the first one passes, and the second one fails. The second one, when run by itself, passes. That means the first one (either the test, or the impl!! it could be either!!!) is doing something to infect the results of the second. It might not be cleaning up after itself. It might be producing some side effect like creating a config file or dynamically generating a method... who knows!?!?

Sometimes I figure it out by what the second test is doing. Sometimes I figure it out by the first. Sometimes, I painfully have to dig down through the implementation to see what's going on.

**Comment by zenspider** [comment]
No response in 2 years... closing
