### ISSUE TITLE
Odd behavior after stubbing Time.now

### ISSUE THREAD

**Issue by pienkowb** [minitest/minitest#843]
Because of the use of `Tempfile` inside the `diff` method, stubbing `Time.now` results in a misleading error message on failed equality assertions.

Example:

```ruby
require 'ostruct'
require 'minitest/autorun'

class ExampleTest < Minitest::Test
  def test_stubbing_time_now
    time = OpenStruct.new(to_i: 1_584_871_827)

    Time.stub(:now, time) do
      expected = '0' * 30
      actual = '1' * 30

      assert_equal expected, actual
    end
  end
end
```

```
# Running:

E

Finished in 0.004237s, 236.0160 runs/s, 236.0160 assertions/s.

  1) Error:
ExampleTest#test_stubbing_time_now:
NoMethodError: undefined method `strftime' for #<OpenStruct to_i=1584871827>
    /Users/pienkowb/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tmpdir.rb:125:in `create'
    /Users/pienkowb/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tempfile.rb:127:in `initialize'
    /Users/pienkowb/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tempfile.rb:287:in `new'
    /Users/pienkowb/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tempfile.rb:287:in `open'
```

This behavior is caused by `Tempfile` using `Time.now` internally ([here](https://github.com/ruby/ruby/blob/master/lib/tmpdir.rb#L133)).

It is not a bug in minitest itself, but maybe it deserves a caution in the [Stubs](https://github.com/seattlerb/minitest#label-Stubs) section of the README file (since stubbing `Time.now` is shown as an example there).

**Comment by zenspider** [comment]
This is a bug because you stubbed `Time.now` with something that isn't a time. This seems unreasonable to me. Stub with an instance of time and it works fine.
