### ISSUE TITLE
mock: Keyword arguments deprecation warning when calling block

### ISSUE THREAD

**Issue by nbering** [minitest/minitest#847]
## Example Code
```ruby
m = Minitest::Mock.new

m.expect(:foo, nil) do |example:|
  example == :bar
end

m.foo(example: :bar)

assert m.verify
```

## Expected

When calling passing a block to `Mock#expects`, Minitest should call the block, and not produce any Ruby warnings.

## Actual

Results in a keyword parameters deprecation warning when the mock framework calls the block.
```
./usr/local/bundle/gems/minitest-5.14.0/lib/minitest/mock.rb:144: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

## Versions
Ruby 2.7.1
Minitest 5.14.0

**Comment by tonytonyjan** [comment]
Here is the PR to fix your issue by supporting keyword arguments in `Minitest::Mock::expect`.

https://github.com/minitest/minitest/pull/908

Your can verify its functionality by:

```sh
git clone -b fix/support-keyword-arguments git@github.com:tonytonyjan/minitest.git &&
  cd minitest &&
  ruby -Ilib -rminitest/autorun <<EOS
class Example < Minitest::Test
  def test_example
    m = Minitest::Mock.new

    m.expect(:foo, nil) do |example:|
      example == :bar
    end

    m.foo(example: :bar)

    assert m.verify
  end
end
EOS
```

**Comment by zenspider** [comment]
This should be handled now. Thank you!
