### ISSUE TITLE
Can I add remarks when writing test_ method under minitest?

### ISSUE THREAD

**Issue by xiaojin2630** [minitest/minitest#854]
I write testcase in python code, and I can add comment information for each test_. This comment will eventually appear in the report. This is a very good idea to enhance the readability of the report. as follows:

    def test_02_bushuru(self):
        '''不输入，点击登录'''
        self.baselei.click(self.loginbutton)
        result2 =self.baselei.find(self.message).text
        print("我是内容test02：",result2)
        exp2 = "请输入手机号码"
        self.assertEqual(result2,exp2)

But when I use minitest + ruby to write a testcase, how do I add this comment under test_?

**Comment by zenspider** [comment]
Interesting... I've always been a bit jealous that python picked up the smalltalk pattern of commenting via a string (not really a string in smalltalk, but it looks like it) and making it available via api.

No, this isn't really a thing in minitest (or ruby for that matter). And by default, the reporting in minitest is very spartan (for passing tests at least)... just a bunch of dots.

But you might want to look at minitest/spec and the use of `describe` + `it` for more textual forms.

**Comment by zenspider** [comment]
No response in a year. Closing.
