### ISSUE TITLE
Is there a way to skip abstract test class registration?

### ISSUE THREAD

**Issue by edenworky** [minitest/minitest#855]
I have two test classes testing two classes, `Die` and `Roll` (which handles collections of dice). Both of these can only be rolled once, a behavior implemented in common parent `Rollable`. This, of course, entails a lot of test duplication regarding this bit of functionality, which I solved by making an abstract `RollableTest` class, containing the shared tests with some implementable methods. However, when I run my tests, the non-implemented abstract tests get run under `RollableTest`, in addition to running for dice and rolls as expected.

I can fix this by skipping the abstract tests when they run directly under the abstract class, but this still skips them rather than not registering them to begin with (polluting the report), and isn't as good as a way to mark the class as abstract or unregistarable or similar. Does minitest support this use case?

_For prosperity: one can elegantly skip tests in this way in the `setup` hook._

**Comment by itsliamegan** [comment]
Not a maintainer, but you could always extract out `RollableTest` to a module instead of a parent class, then include this module in both the `DieTest` and `RollTest`. It might necessitate that you change the structure of `RollableTest` a bit, but it will also probably signal "these things both have this common behavior" clearer.

**Comment by zenspider** [comment]
There is no feature in minitest to mark some test class as "abstract" such that that class isn't registered to run. Here's how I generally look at things:

```ruby
require "minitest/autorun"

# For the most part, I find testing should reflect the
# implementation's general architecture (pretty close to) 1:1:

# Given:
#
# Specialization < GeneralThingy
#
# One would generally test with something like:
#
# TestGeneralThingy
# TestSpecialization < TestGeneralThingy
#
# where most tests were inherited, but any overrides on the part of
# Specialization would also be overridden as needed.

class TestGeneralThingy
  def test_generic_feature
    assert true
  end

  def test_overridden_feature
    assert true
  end
end

class TestSpecialization < TestGeneralThingy
  def test_overridden_feature
    # ... something different ?
  end
end

# Given classes:
#
# Concrete1 & Concrete2
#
# two or more classes that might use one another but aren't "is-a"
# relationships, one would generally test them independently.
#
# If, however, they have some feature or constraint in common (eg can
# only X once), you might push that functionality up to an abstract
# class (eg Xable) and you would test similarly:
#
# class Xable
# class Concrete1 < Xable
# class Concrete2 < Xable

class AbstractTest < Minitest::Test
  def setup
    skip if self.class == AbstractTest
  end

  def test_abs_1
    assert true
  end

  def test_abs_2
    assert true
  end
end

class Concrete1 < AbstractTest
end

class Concrete2 < AbstractTest
end

# (resulting in 6 runs w/ 2 skips)

# or you might push that testing into its own module (which you might
# want to do in the implementation as well):
#
# module Xable
# class Concrete1; include Xable
# class Concrete2; include Xable

module TestXable
  def test_abs_1
    assert true
  end

  def test_abs_2
    assert true
  end
end

class Concrete1 < Minitest::Test
  include TestXable
end

class Concrete2 < Minitest::Test
  include TestXable
end

# (resulting in 4 runs only)
```

**Comment by zenspider** [comment]
No response. Closing.
