### ISSUE TITLE
obj.must_raise deprecation and more info

### ISSUE THREAD

**Issue by mperham** [minitest/minitest#856]
I got this in the Dalli test suite:

```
DEPRECATED: global use of must_raise from /Users/mikeperham/src/dalli/test/test_server.rb:144. Use _(obj).must_raise instead. This will fail in Minitest 6.
```

I've never seen this syntax before `_(obj)`, I have no idea what it is, how it works and I found one mention in the README that didn't help. The name `_` is impossible to search for, I didn't see anything in History. The suggested syntax breaks my test so I'm not sure what to do now.

I generally output a link to an issue/PR with more info for each deprecation so that I can add more context or answer questions, e.g.

```
DEPRECATED: global use of must_raise from /Users/mikeperham/src/dalli/test/test_server.rb:144. Use _(obj).must_raise instead. See https://github.com/seattlerb/minitest/issues/12345 for more info.
```

Can you give me any pointers here? I'm doing this:

```ruby
lambda { Dalli::Server.new('[]') }.must_raise Dalli::DalliError
```

**Comment by blowmage** [comment]
It should say something like `Use _{ obj.method }.must_raise` instead. Also, remember that `value` and `expect` are aliases for `_`, and can be used with blocks as well. e.g. `expect{ obj.method }.must_raise`

So for your specific snippet, I would say:

```ruby
expect { Dalli::Server.new('[]') }.must_raise Dalli::DalliError
```

**Comment by mperham** [comment]
@blowmage Thanks for the context. This would be super useful in the README; I'd send a PR but I don't have a good sense for the overall picture that needs to be documented. I had no idea minitest even supported an `expect` DSL.

**Comment by blowmage** [comment]
My understanding is that the expectation methods (`must_` and `wont_`) will no longer be added to `Object` in Minitest 6. The `_`/`value`/`expect` methods will be the only way to obtain an object that does have the expectation methods.

This change is being made for the same reasons Rspec stopped monkey patching `Object`. You can get pretty far in Minitest with this now if you set a `MT_NO_EXPECTATIONS` environment variable before loading minitest, which will [skip said monkey patch](https://github.com/seattlerb/minitest/blob/15ed8e4ce504c8313058a1d6fc4918299be34328/lib/minitest/spec.rb#L340-L342).

**Comment by zenspider** [comment]
Is this closable Mike(s—haha)?

PR for readme is welcome.

**Comment by blowmage** [comment]
If @mperham is satisfied then I think this can be closed.

I can take a swing at updating the README, but it might be a week or so until I get something.

**Comment by mperham** [comment]
What has changed? My original issue was with an unhelpful error message. Has that message changed or documentation added?

**Comment by blowmage** [comment]
All of the code examples look to be changed to use the `_().must_` syntax. e.g. [`#must_raise`](https://ruby-doc.org/stdlib-3.0.2/libdoc/minitest/rdoc/Minitest/Expectations.html#method-i-must_raise). The README doesn't explicitly mention the deprecation of the old syntax however.

@mperham can you provide us an example of what you would consider a more helpful deprecation message?

@zenspider can you help set expectations on how much method documentation you are willing to accept? Currently `#must_raise` has the following documentation:

```ruby
##
# See Minitest::Assertions#assert_raises
#
#    _ { ... }.must_raise exception
#
# :method: must_raise
```

Would the following be accepted?

```ruby
##
# Fails unless the block raises one of +exp+. Returns the
# exception matched so you can check the message, attributes, etc.
#
# +exp+ takes an optional message on the end to help explain
# failures and defaults to StandardError if no exception class is
# passed. Eg:
#
#    _ { method_with_custom_error }.must_raise exception(CustomError)
#
# With custom error message:
#
#    _ { method_with_custom_error }.must_raise exception(CustomError, 'This should have raised CustomError')
#
# Using the returned object:
#
#   error = _ { raise CustomError, 'This is really bad' }.must_raise exception(CustomError)
#
#   _(error.message).must_equal 'This is really bad'
#
# See Minitest::Assertions#assert_raises
#
# ### Deprecated Syntax
#
# Expectations can be called on Object are deprecated and will be removed in Minitest 6.
# Use Minitest::Spec::DSL::InstanceMethods#_ instead.
#
# :method: must_raise
# :args: *exp
```

**Comment by mperham** [comment]
I think I just uncomfortable with the use of `_` as test syntax. The issue is that underscore method is not self-describing and reads like magic. I would prefer `expect` or another word which indicates intent. IME `_` is universally used as shorthand for "the code does not use this argument" and this usage reads like Perl or Bash, not idiomatic Ruby.

I see that the examples in the README have been updated and that `minitest/spec` contains two aliases for `_`, `value` and `expect`. Maybe you could document those two aliases so people can use whichever alias reads the best for their spec?

**Comment by blowmage** [comment]
So are you saying that the deprecation message is acceptable as is?

**Comment by mperham** [comment]
Add a link. If you are going to tell people that a certain syntax is
deprecated, I think the message should include a link to a page which
explains and shows the recommended syntax. It could just be a link to
spec’s RDoc.

**Comment by zenspider** [comment]
https://docs.seattlerb.org/

**Comment by tannerburson** [comment]
I ran into the same issue as @mperham , I was not familiar with the seemingly magic `_` method, or its use in the `Spec` context for Minitest. The only documentation I could find for this syntax is: https://docs.seattlerb.org/minitest/Minitest/Spec/DSL/InstanceMethods.html, which is pretty sparse. I'm not sure if the right solution is to beef up that documentation, or add something similar to what @blowmage suggested to the README about syntax.

**Comment by zenspider** [comment]
> All of the code examples look to be changed to use the `_().must_` syntax. e.g. [`#must_raise`](https://ruby-doc.org/stdlib-3.0.2/libdoc/minitest/rdoc/Minitest/Expectations.html#method-i-must_raise). The README doesn't explicitly mention the deprecation of the old syntax however.
> 
> @mperham can you provide us an example of what you would consider a more helpful deprecation message?
> 
> @zenspider can you help set expectations on how much method documentation you are willing to accept?
>  ...

Yes, the above seems fine. Please submit a PR

**Comment by blowmage** [comment]
> Yes, the above seems fine. Please submit a PR

@zenspider Ugh, I didn't see your reply until you closed this. I'll try to get a PR in for a doc pass this week.
