### ISSUE TITLE
How to test different implementation of an interface

### ISSUE THREAD

**Issue by nvoynov** [minitest/minitest#889]
Hi,

I have one interface of a data gateway and a few implementations of this interface - InMemory, PStore, Sequel. Can I have only one test_source_code that will test all those implementations? Of course, I could just copy files and change the target implementations, but I'll have a few files with the same test code, that differs only by one string of code.

```ruby
describe SequelGateway do
  let(:gateway) { SequelGateway.new } # MemoryGateway, PStoreGateway, ...
  # few hundreds of lines of the interface skipped
  # ...
end
```

**Comment by adam12** [comment]
Put the tests/specs in a `module` and then include that module into your `describe` blocks.

```ruby
require "minitest/autorun"

module SharedSpecs
  extend Minitest::Spec::DSL

  it "does something" do
    refute_nil gateway
  end
end

describe "Something" do
  include SharedSpecs

  let(:gateway) { }
end
```

**Comment by nvoynov** [comment]
It works, thanks a lot! But how about nested `describe` blocks? Is it possible to write nested `describe` blocks in this shared module? I tried to change your example as follows 

```ruby 
require "minitest/autorun"

module SharedSpecs
  extend Minitest::Spec::DSL

  describe "something" do
    it "does something" do
      refute_nil gateway
    end
  end
end

describe "Something" do
  include SharedSpecs

  let(:gateway) { }
end
```

and it fails this way

```
  1) Error:
something#test_0001_does something:
NameError: undefined local variable or method `gateway' for #<#<Class:0x0000020f5a256780>:0x0000020f5a166500 @NAME="test_0001_does something", @failures=[#<Minitest::UnexpectedError: Unexpected exception>], @assertions=0, @time=0.00020090000180061907>
    C:/Users/Nick/src/ruby/cleon_sandbox/users-api/test/newg/example.rb:9:in `block (2 levels) in <module:SharedSpecs>'

  2) Error:
something#test_0002_does something real:
NameError: undefined local variable or method `gateway' for #<#<Class:0x0000020f5a256780>:0x0000020f5a15bdd0 @NAME="test_0002_does something real", @failures=[#<Minitest::UnexpectedError: Unexpected exception>], @assertions=0, @time=0.00011410000297473744>
    C:/Users/Nick/src/ruby/cleon_sandbox/users-api/test/newg/example.rb:13:in `block (2 levels) in <module:SharedSpecs>'
```

my desired implementation [in this gist](https://gist.github.com/nvoynov/218b2697b825afc3ae716ff6d1ea093e)

**Comment by zenspider** [comment]
`describe` creates test classes, not modules... and nesting modules doesn't inherit methods of the parent modules... So you're going to want something more like:

```ruby
module SharedSpecs
  module SomethingTest
    extend Minitest::Spec::DSL

    it "does something" do
      refute_nil gateway
    end
  end
end

describe "Something" do
  include SharedSpecs::SomethingTest

  let(:gateway) { }
end
```

But I'm going to suggest something crazy here:

# Stop

You're trying to be clever and reuse a bunch of tests via very indirect means. You want the shared code to "reach down" to get values like `gateway`. I can tell you, after 22 years of ruby, maaany years of consulting, and the nightmares of rspec I've had to debug (where I usually see this pattern)... STOP.

Use classes. Inherit methods (even test methods). Write your tests as simply as possible. Yes, even if that means code duplication in a couple places. If someone has to scroll up AND down in a file just to figure out how you wired up a test, you've failed the complexity test. 

Trust me on this. Try it and see.

**Comment by nvoynov** [comment]
At that time I explored the possibility I finished with modules. You can see my shared specs [shared_gateway_specs.rb](https://github.com/nvoynov/cleon-users-api/blob/master/test/users_api/shared_gateway_specs.rb) and its using in [gateway_spec.rb](https://github.com/nvoynov/cleon-users-api/blob/master/test/users_api/gateway_spec.rb) and [memory_gateway_spec.rb](https://github.com/nvoynov/cleon-users-api/blob/master/test/users_api/memory_gateway_spec.rb)

And thank you for the "stop" heads-up! Yes, sometimes I had some difficulties catching test problems with variables with the same name inside two or more tests like `let(:gateway) { MemoryGateway.new }` and `let(:gateway) { Gateway.new }`. But maybe my the very first request for sharing wasn't 100% correct. In fact, I just wanted to avoid developing a true gateway and the simplest possible hash-based gateway was enough for that moment. But anyway I can't see Ruby code without tests, so I covered it with tests. And finally, I've added a real gateway and want to use tests that are actually ready and should be reused.

So I still think it is a good idea to share some test code to test different implementations of the same logic.

**Comment by zenspider** [comment]
Assuming your issue is handled, please close.
