### ISSUE TITLE
around hooks

### ISSUE THREAD

**Issue by akostadinov** [minitest/minitest#892]
Please implement `around` hooks alongside `setup` and `teardown`. That's very useful depending on libraries available helper methods.

FYI there is a separate project that tried to do so in non-ideal way

https://github.com/splattael/minitest-around/blob/master/lib/minitest/around/unit.rb

**Comment by zenspider** [comment]
I'm uninterested in adding this to _mini_ test.

There's also minitest-hooks which seems to work fine.
