### ISSUE TITLE
I wish assert_match was exposing the matchdata somehow

### ISSUE THREAD

**Issue by Nakilon** [minitest/minitest#900]
I wish I could do just this
```ruby
assert_match /\APRIVMSG #channel :(.+)\n\z/, @client.gets.force_encoding("utf-8")
$1
```
or something like
```ruby
assert_match /\APRIVMSG #channel :(.+)\n\z/, @client.gets.force_encoding("utf-8")
Minitest::matchdata[1]
```
instead of defining vars and matching twice
```ruby
    r, s = /\APRIVMSG #channel :(.+)\n\z/, @client.gets.force_encoding("utf-8")
    assert_match r, s
    s[r, 1]
```

UPD: also:
```ruby
    r, s = /\APRIVMSG #channel :(?<reply>.+)\n\z/, gets
    assert_match r, s
    refute_match expectation, s[r,1]
```
to
```ruby
    assert_match /\APRIVMSG #channel :(?<reply>.+)\n\z/, gets
    refute_match expectation, Minitest::matchdata.named_captures[:reply]]
```

**Comment by zenspider** [comment]
Unfortunately the `$1` vars are all scoped to the calling method so they're not available where you call `assert_match`. That would have been nice and easy, but noooo...

What do you think about `m = assert_match ...` to get the match data? `assert_raises` returns the exception raised in a similar fashion.

**Comment by Nakilon** [comment]
> to get the match data

You mean to return? Sounds nice. I don't remember if I checked what the `assert_` returns right now, maybe it's vacant.

**Comment by zenspider** [comment]
This is impremented... will go out in the next release.
