### ISSUE TITLE
Certificate expiry blocking application builds

### ISSUE THREAD

**Issue by sronsiek** [minitest/minitest#901]
I built a docker container for a rails app last year - now we're getting ready for release I tried a re-build.

OS: SLES15sp3 with native ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux-gnu]
Bundler version 2.3.7

Gemfile:
```
source 'https://rubygems.org'
gem 'rails', '= 5.2.6'
```

`bundle install`

... after installing a load of gems successfully, fails with:

_The gem minitest-5.15.0 can't be installed because the security policy didn't
allow it, with the message: missing digest for metadata.gz_

`bundle install --trust-policy=LowSecurity`

... after installing a load of gems successfully, fails with:

_The gem minitest-5.15.0 can't be installed because the security policy didn't
allow it, with the message: **certificate /CN=ryand-ruby/DC=zenspider/DC=com not
valid after 2021-12-22 20:38:30 UTC**_

Same results for minitest-5.14.4.

It is unclear where bundler is attempting to access this cert.

Is there any / fix workaround for this? 

This is completely blocking all progress on our project which is due for delivery shortly. Anoyingly we probably don't even need minitest in production - but there seems to be no way to exclude what must be a dependency of a core gem.

Any help would be highly appreciated!!

**Comment by sronsiek** [comment]
Ok, found the location: `minitest.gemspec` contains `s.cert_chain` set to a certificate string, which, when decoded, reveals the expiry cert date in the error message:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 5 (0x5)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = ryand-ruby, DC = zenspider, DC = com
        Validity
            Not Before: Dec 22 20:38:30 2020 GMT
            Not After : Dec 22 20:38:30 2021 GMT
        Subject: CN = ryand-ruby, DC = zenspider, DC = com
```

So I guess a release with an updated cert is required, yes?

**Comment by sronsiek** [comment]
So - the errors can be avoided by disabling security checks with one of the following:

`echo ":ssl_verify_mode: 0" > $HOME/.gemrc`

`bundle config ssl_verify_mode '0'`

However lowering security does not realyy seem to be the answer.
Certificates with 1 yr validity also seem far from ideal.

Seems to me that certs are not the ideal way to sign gems - gpg keys seem more appropriate, but this is a debate larger than a single gem ...

**Comment by zenspider** [comment]
```
9979 % grep ^= History.rdoc  | head 
=== 5.15.0 / 2021-12-14
=== 5.14.4 / 2021-02-23
=== 5.14.3 / 2021-01-05
=== 5.14.2 / 2020-08-31
=== 5.14.1 / 2020-05-15
=== 5.14.0 / 2020-01-11
=== 5.13.0 / 2019-10-29
=== 5.12.2 / 2019-09-28
=== 5.12.1 / 2019-09-28
=== 5.12.0 / 2019-09-22
```

Is the above Validity range for ME, or for minitest? If minitest, it doesn't line up with ANY of my releases... if ME, then I probably released something on that date and then signed/released minitest and then the stupid thing expired mere days afterward? Seems really dumb to me... but signing on rubygems has always been an afterthought and kinda screwy.

rereleasing old versions in order to get them retagged is not in my best interest... that's a losing battle.

I'm happy to take suggestions on how to better sign/release in the future tho. I'm not a black hat by ANY means and so my eyes glaze over when this stuff comes up.

**Comment by zenspider** [comment]
I've released a new version of minitest. This doesn't fix the long-term issue... but I think that's on rubygems/rubygems to fix, not me. Closing.
