### ISSUE TITLE
When minitest work with a callable object, the behavior may unexpected.

### ISSUE THREAD

**Issue by zw963** [minitest/minitest#907]
Maybe this not a issue, but because this behavior, i spent a hour time to find out why.

Following is a example, i use [mock-redis](https://github.com/sds/mock_redis) for mock redis to a memory redis.

So, i write following code:

```rb
  def around
    mock_redis = MockRedis.new
    RedisHelper.stub :connect, mock_redis do
      super
    end
  end
```
Then i always get error like this:

```
gems/mock_redis-0.31.0/lib/mock_redis.rb:53:in `call': wrong number of arguments (given 0, expected 1) (ArgumentError)                                                
        ruby-3.1.0/lib/ruby/gems/3.1.0/gems/minitest-5.15.0/lib/minitest/mock.rb:229:in `block in stub'
        from //test/graphql/mutations/chat_mutations/refund_transfer_test.rb:3:in `block in <class:RefundTransferTest>'
        from <internal:prelude>:5:in `irb'                
        from //test/graphql/mutations/chat_mutations/refund_transfer_test.rb:79:in `block in <class:RefundTransferTest>'
        ruby-3.1.0/lib/ruby/gems/3.1.0/gems/minitest-5.15.0/lib/minitest/test.rb:98:in `block (3 levels) in run'
        ruby-3.1.0/lib/ruby/gems/3.1.0/gems/minitest-5.15.0/lib/minitest/test.rb:195:in `capture_exceptions'
        ruby-3.1.0/lib/ruby/gems/3.1.0/gems/minitest-5.15.0/lib/minitest/test.rb:95:in `block (2 levels) in run'
        from gems/minitest-hooks-1.5.0/lib/minitest/hooks/test.rb:38:in `block (2 levels) in time_it'
        from gems/minitest-hooks-1.5.0/lib/minitest/hooks/test.rb:31:in `around'
```

I spent more than one hour to find out why this happen, because it not raise this error when i pass a real object instead. e.g.

```rb
    mock_redis = 100
    RedisHelper.stub :connect, mock_redis do
      super
    end
```

Finally i find the reason, because ` MockRedis.new` respond to call, but that completely unexpected for me, i don't know that :call method exists.

```rb
metaclass.send :define_method, name do |*args, &blk|
  if val_or_callable.respond_to? :call then
    val_or_callable.call(*args, &blk)
  else
    blk.call(*block_args) if blk
    val_or_callable
  end
end
```

So, maybe a better solution is, if minitest invoke `object.call` instead of `object`, it should output a warn or message or something.

Thank you.

**Comment by zenspider** [comment]
You have a stacktrace that points at thes lines:

https://github.com/minitest/minitest/blob/v5.15.0/lib/minitest/mock.rb#L228-L229

At that point you know that your MockRedis object responds to `call`. The first line says it. The second line confirms it. The error raised cements it.

Looking up a wee bit, you see:

https://github.com/minitest/minitest/blob/v5.15.0/lib/minitest/mock.rb#L196-L198

which documents this behavior. 

You want it to _warn_ the user if it is doing what it is documented to do? What would it warn?

**Comment by zw963** [comment]
It' ok, maybe because i rarely used minitest stub or MockRedis gem, which cause this trouble

thank you for help!
