### ISSUE TITLE
Expected block yield behavior for Mock#stub?

### ISSUE THREAD

**Issue by phoebetse** [minitest/minitest#914]
## Context
I was following the (several years old) [tutorial](https://mixandgo.com/learn/ruby/minitest-rspec) on using `minitest` mocks with block yielding: https://github.com/mixandgo/blog_testing_blocks/blob/master/example_test.rb. However, I was unable to get it to work myself. 

It looked like the callable (`conn_info` in the linked tutorial) was called, but my `block_args` (`sftp_mock` in the tutorial) was not being passed along to the stub. As a result, the `sftp_mock` expectation was failing.

I dug into the minitest source code a bit, and noticed the following

https://github.com/minitest/minitest/blob/master/lib/minitest/mock.rb#L267
```ruby
# lib/minitest/mock.rb
 metaclass.send :define_method, name do |*args, **kwargs, &blk|
      if val_or_callable.respond_to? :call then
        ...
          val_or_callable.call(*args, **kwargs, &blk)
      else
        if blk then
            ...
            blk.call(*block_args, **block_kwargs)
        end
        val_or_callable
      end
    end
```
as well as the following commit: https://github.com/minitest/minitest/commit/ac9eaef79bcd6e1a5b30d89c8e43cf99eea30178

## Workaround
From looking at the source code and that old commit, I found a workaround by separating my tests so that one test used a stub with just `Net::SFTP.stub(:start, conn_info)` and another with `Net::SFTP.stub(:start, true, sftp_mock)` so that the latter would correctly pass my block along to the stub.

However, I would've expected that if I had `Net::SFTP.stub(:start, conn_info, sftp_mock)`, the `sftp_mock` block would be passed along to the stub and that `sftp_mock.verify` would return true. 

## Question:
What is the expected behavior for block yielding?

If my workaround here is the intended use for `stub`, maybe we could update the [documentation](https://www.rubydoc.info/gems/minitest/Object:stub) to explain this a bit better? 

Thank you!

**Comment by zenspider** [comment]
This is intentional:

https://github.com/minitest/minitest/blob/master/History.rdoc#5110b1--2017-12-20-

specifically:

> Object.stub no longer calls the passed block if stubbed with a callable.
> Object.stub now passes blocks down to the callable result.

so the proper way is to rearrange your code and add this at the end of your conn_info block (w/ a new `&block` arg):

```ruby
      block.call sftp_mock
```
