### ISSUE TITLE
Visual Studio Code Test Explorer stopped working (5.16.1)

### ISSUE THREAD

**Issue by finnove** [minitest/minitest#917]
Working fine on 5.15.0. Not working on 5.16.1. Using VS Code Test Explorer with Ruby Test Explorer extention.
https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer
https://marketplace.visualstudio.com/items?itemName=connorshea.vscode-ruby-test-adapter

[2022-06-23 20:40:28.945] [INFO] Configuration changed
[2022-06-23 20:40:28.945] [INFO] Killing currently-running tests.
[2022-06-23 20:40:28.945] [INFO] Loading Ruby tests...
[2022-06-23 20:40:28.945] [INFO] Loading Minitest tests...
[2022-06-23 20:40:28.946] [INFO] Getting a list of Minitest tests in suite with the following command: bundle exec rake -R $EXT_DIR vscode:minitest:list
[2022-06-23 20:40:29.919] [ERROR] Error while finding Minitest test suite: Command failed: bundle exec rake -R $EXT_DIR vscode:minitest:list
rake aborted!
TypeError: no implicit conversion of nil into Integer
/home/fol/.rvm/gems/ruby-2.7.2/gems/minitest-5.16.1/lib/minitest/test.rb:70:in `srand'
/home/fol/.rvm/gems/ruby-2.7.2/gems/minitest-5.16.1/lib/minitest/test.rb:70:in `runnable_methods'
/home/fol/.vscode-server/extensions/connorshea.vscode-ruby-test-adapter-0.9.0/ruby/vscode/minitest/tests.rb:33:in `block in build_list'
/home/fol/.vscode-server/extensions/connorshea.vscode-ruby-test-adapter-0.9.0/ruby/vscode/minitest/tests.rb:32:in `map'
/home/fol/.vscode-server/extensions/connorshea.vscode-ruby-test-adapter-0.9.0/ruby/vscode/minitest/tests.rb:32:in `build_list'
/home/fol/.vscode-server/extensions/connorshea.vscode-ruby-test-adapter-0.9.0/ruby/vscode/minitest/tests.rb:9:in `all'
/home/fol/.vscode-server/extensions/connorshea.vscode-ruby-test-adapter-0.9.0/ruby/vscode/minitest.rb:25:in `list'
/home/fol/.vscode-server/extensions/connorshea.vscode-ruby-test-adapter-0.9.0/ruby/vscode.rake:8:in `block (3 levels) in <main>'
/home/fol/.rvm/gems/ruby-2.7.2/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/fol/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `eval'
/home/fol/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => vscode:minitest:list
(See full trace by running task with --trace)

**Comment by zenspider** [comment]
This would be an issue w/ vscode ... if they're running the tests directly and not through my top-level method, then they've got to set `Minitest.seed=xxx`

**Comment by ghiculescu** [comment]
cc @connorshea - a fix probably looks like this https://github.com/qrush/m/pull/92

**Comment by blowmage** [comment]
Oh yeah, I should probably reference connorshea/vscode-ruby-test-adapter#100 here, right?

**Comment by finnove** [comment]
> This would be an issue w/ vscode ... if they're running the tests directly and not through my top-level method, then they've got to set `Minitest.seed=xxx`

...May I suggest that seed would be made optional when running a test directly...(or auto set to some default value if not provided) The tests in test explorer was running in sequential order.. but I am totally fine with that for now. At least it was stable. Btw when switching to the built in / official vscode test adapter the tests are running at random... but then the tests will not complete...just some of them. Don't know why that is...(not related to this 5.16.1. version.)

**Comment by finnove** [comment]
> Oh yeah, I should probably reference [connorshea/vscode-ruby-test-adapter#100](https://github.com/connorshea/vscode-ruby-test-adapter/pull/100) here, right?

Perfect! I tried your updated Ruby Test Explorer v0.9.1 now, and it seem to have solved the problem for now. Thank you so much!
![Code_Wn1rHCyhp9](https://user-images.githubusercontent.com/1630604/185871077-76462518-ea4f-41a9-8d90-fef80fd2ac59.png)
!

**Comment by blowmage** [comment]
Closing as the fix offered in connorshea/vscode-ruby-test-adapter#100 was accepted and merged.
