### ISSUE TITLE
MFA is required on your rubygems.org account

### ISSUE THREAD

**Issue by sonalkr132** [minitest/minitest#924]
Hi, I am reaching out on the behalf of rubygems.org team to let you know that you won't able to publish gems using [zenspider](https://rubygems.org/profiles/zenspider) account because your gems have more than 180 mil downloads and you have not enabled mfa on your account. You should have received email notifications about the same.
We humbly request that you enable at least ["ui and gem signin"](https://guides.rubygems.org/setting-up-multifactor-authentication/#authentication-levels) level for your account as soon as possible to avoid any unwanted disruption. You can check our [announcement post](https://blog.rubygems.org/2022/08/15/requiring-mfa-on-popular-gems.html) for more details. 
Please let us know if you have any questions or need any help.

**Comment by zenspider** [comment]
UGH

**Comment by zenspider** [comment]
After having done a few releases under this... actual hate rather than anticipatory hate

**Comment by sonalkr132** [comment]
We would be more than happy if you could spare a few moments for your feedback. Why do you think the current process not work for you? Which MFA level are you using? What do you think we could do differently?

You can either leave your comments here or on our issue tracker https://github.com/rubygems/rubygems.org/issues
