### ISSUE TITLE
MiniTest::Mock and the debug gem 

### ISSUE THREAD

**Issue by keithlayne** [minitest/minitest#929]
Not sure where to ask this, or if it would be considered a bug on either side, but:

I just updated a project to ruby 3, and started using the `debug` gem. I haven't experiemented a whole lot, but generally it seems that having `debug` loaded causes my previous usage of `MiniTest::Mock` to error. Here's a rough example:

```rb
class FooTest < ActionDispatch::IntegrationTest
  def stub_foot(&)
    foo = MiniTest::Mock.new
    def foo.bar = 'very awesome foo'
    Baz.stub(:foo, foo, &)
  end
  # ...tests
end
```

This gets an error like:

```sh
Error:
FooTest#test_quux: NoMethodError: unmocked method :singleton_method_added, expected one of []
```

Looks like `debug` is hooking into `BasicObject#singleton_method_added`, and that is causing shenanigans here. On a whim, I tried `foo = MiniTest::Mock.new(BasicObject)`, which _seems_ to work. All my tests that use mocks are now happy. 

I have no clue if this is the right answer - any help would be appreciated. Also, would like to know if this should be considered a bug, and if so, who should own it.

**Comment by dentarg** [comment]
Similar issue reported at https://github.com/ruby/debug/issues/757

**Comment by zenspider** [comment]
Minimal repro:

```ruby
require "debug"

class Mock
  overridden_methods = %w[
    ===
    class
    inspect
    instance_eval
    instance_variables
    object_id
    public_send
    respond_to_missing?
    send
    to_s
  ]

  instance_methods.each do |m|
    undef_method m unless overridden_methods.include?(m.to_s) || m =~ /^__/
  end

  def method_missing sym, *args, **kwargs, &block # :nodoc:
    raise NoMethodError, "unmocked method %p" % [sym]
  end
end

foo = Mock.new
def foo.bar = 'very awesome foo'

p :GOOD
```

**Comment by zenspider** [comment]
This should be fixed. Thanks!
