### ISSUE TITLE
Why "Use assert_nil if expecting nil"?

### ISSUE THREAD

**Issue by akimd** [minitest/minitest#930]
Hi,

I'd like to understand why `assert_equal ref, actual` is announced to no longer be supported when `ref` is `nil` in Minitest 6.

I perfectly understand that `assert_equal nil, actual` is bad style, but I have many tests that check computations by running two different implementations, and they possibly can return `nil`.  So `assert_equal res1, res2` is exactly what I mean, including the case where `res1` is nil.

Sure, I can have an `if` around to go to either `assert_equal` or `assert_nil`, but why this added complexity?

Alternatively, I can use `value(actual).must_be :==, ref`, but that somewhat obfuscates the test, and I don't know if some day Minitest won't complain about `you should use must_equal rather than .must_be :==`...

Cheers!

**Comment by vlad-pisanov** [comment]
See https://github.com/minitest/minitest/issues/666 for discussion

If you want, you can silence the warning by monkey-patching `assert_equal` in your `test_helper.rb`:

```ruby
module Minitest
  module Assertions
    def assert_equal(exp, act, msg = nil)
      assert exp == act, message(msg, E) { diff exp, act }
    end
  end
end
```

**Comment by zenspider** [comment]
https://github.com/minitest/minitest/issues?q=is%3Aissue+assert_nil+is%3Aclosed
