### ISSUE TITLE
Create setup array equivalent to `TEARDOWN_METHODS`?

### ISSUE THREAD

**Issue by MSP-Greg** [minitest/minitest#931]
[minitest-proveit](https://github.com/seattlerb/minitest-proveit) uses code [`TEARDOWN_METHODS << "assert_proven?"`](
https://github.com/seattlerb/minitest-proveit/blob/1d86852bd820e1dc4f2d204231f1ebbc1b146075/lib/minitest/proveit.rb#L31) to add a teardown method.

Having an array for setup methods would be helpful for test suites with 'complex helper systems'.

Or, replace code in line 96:
https://github.com/minitest/minitest/blob/b5565c0c7ab2ce5ecf306487cab0f2abe5377d55/lib/minitest/test.rb#L92-L107
with 
```ruby
SETUP_METHODS.each { |hook| self.send hook }
```

Thoughts?

**Comment by zenspider** [comment]
I like it

**Comment by MSP-Greg** [comment]
PR?

**Comment by zenspider** [comment]
Damni. I missed the notification for this. I got ya.

**Comment by zenspider** [comment]
https://github.com/minitest/minitest/commit/3a77687e8b52f4fed90182983b770d7d210ad183 You want to see anything else?

I'm torn on whether to document these or not.

**Comment by MSP-Greg** [comment]
> Damnit. I missed the notification for this.

No problem.   Miss plenty myself.

> I got ya.

Thank you.

> I'm torn on whether to document these or not.

Your call.  I'll make use of it, but there will probably be a few people that overlook its effects.  Or, 'more support'...
