### ISSUE TITLE
How to run skipped test? if I don't want to comment "skip"

### ISSUE THREAD

**Issue by zzz6519003** [minitest/minitest#952]
like
```
require 'minitest/autorun'
require_relative 'acronym'

class AcronymTest < Minitest::Test
  def test_basic
    # skip
    assert_equal "PNG", Acronym.abbreviate('Portable Network Graphics')
  end

  def test_lowercase_words
    skip
    assert_equal "ROR", Acronym.abbreviate('Ruby on Rails')
  end

  def test_punctuation
    skip
    assert_equal "FIFO", Acronym.abbreviate('First In, First Out')
  end

  def test_all_caps_word
    skip
    assert_equal "GIMP", Acronym.abbreviate('GNU Image Manipulation Program')
  end

  def test_punctuation_without_whitespace
    skip
    assert_equal "CMOS", Acronym.abbreviate('Complementary metal-oxide semiconductor')
  end

  def test_very_long_abbreviation
    skip
    assert_equal "ROTFLSHTMDCOALM",
      Acronym.abbreviate('Rolling On The Floor Laughing So Hard That My Dogs Came Over And Licked Me')
  end

  def test_consecutive_delimiters
    skip
    assert_equal "SIMUFTA", Acronym.abbreviate('Something - I made up from thin air')
  end
end

```

**Comment by zenspider** [comment]
You remove skip. I suggest you remove ALL your skips and then run the tests you DO want to run with `-n /regexp/`. That how I do it when I'm plowing through a large set of new tests... usually using the regexps to activate "keywords" as I implement/fix them.

**Comment by zzz6519003** [comment]
close #952







                       
Original
                       
                     

From:"Ryan Davis"< ***@***.*** &gt;;

Date:2023/6/10 6:22

To:"minitest/minitest"< ***@***.*** &gt;;

CC:"Snowmanzzz(Zhengzhong Zhao)"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [minitest/minitest] How to run skipped test? if I don't want tocomment "skip" (Issue #952)




 
You remove skip. I suggest you remove ALL your skips and then run the tests you DO want to run with -n /regexp/. That how I do it when I'm plowing through a large set of new tests... usually using the regexps to activate "keywords" as I implement/fix them.

**Comment by zzz6519003** [comment]
Closes:&nbsp;#952







                       
Original
                       
                     

From:"Ryan Davis"< ***@***.*** &gt;;

Date:2023/6/10 6:22

To:"minitest/minitest"< ***@***.*** &gt;;

CC:"Snowmanzzz(Zhengzhong Zhao)"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [minitest/minitest] How to run skipped test? if I don&#39;t want tocomment &quot;skip&quot; (Issue #952)




 
You remove skip. I suggest you remove ALL your skips and then run the tests you DO want to run with -n /regexp/. That how I do it when I'm plowing through a large set of new tests... usually using the regexps to activate "keywords" as I implement/fix them.

**Comment by zzz6519003** [comment]
Closes: #952







                       
Original
                       
                     

From:"Ryan Davis"< ***@***.*** &gt;;

Date:2023/6/10 6:22

To:"minitest/minitest"< ***@***.*** &gt;;

CC:"Snowmanzzz(Zhengzhong Zhao)"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [minitest/minitest] How to run skipped test? if I don&#39;t want tocomment &quot;skip&quot; (Issue #952)




 
You remove skip. I suggest you remove ALL your skips and then run the tests you DO want to run with -n /regexp/. That how I do it when I'm plowing through a large set of new tests... usually using the regexps to activate "keywords" as I implement/fix them.

**Comment by zenspider** [comment]
???

**Comment by abatko** [comment]
The `-n /regexp/` form is not working for me:

```
bundle exec rails test test/integration/my_cool_test.rb -n /user registration/

kernel_require.rb:32:in `require': cannot load such file -- /Users/me/lalala/registration (LoadError)
```

...whereas the underscored form is working:
```
bundle exec rails test test/integration/my_cool_test.rb -n test_caregiver_registration
```

I am using `minitest (5.18.0)`.
