### ISSUE TITLE
JUnitReporter seems to silence seed 

### ISSUE THREAD

**Issue by mikevoets** [minitest/minitest#955]
## Overview

We have a problem with the "# Running tests with run options --seed 52273:" not outputting when we run the tests with a JUnitReporter.

## Repro steps

```
reporters = [Minitest::Reporters::DefaultReporter.new(color: true)]
reporters << Minitest::Reporters::JUnitReporter.new('test/reports', true, { single_file: true })
Minitest::Reporters.use!(reporters)
```

## Expected behaviour

"# Running tests with run options --seed 52273:" is outputted in stdout when we run the tests.

## Actual behaviour 

We don't get such output.

## Note

When we remove the JUnitReporter, the expected behaviour occurs.

**Comment by zenspider** [comment]
No response. Closing. Please file this against Minitest::Reporters.
