### ISSUE TITLE
Make Minitest::Result extendable

### ISSUE THREAD

**Issue by matteeyah** [minitest/minitest#956]
## Summary

I want to add additional metadata about a test to `Minitest::Result`. There's currently no way to do that other than opening and redefining `Minitest::Result.from` which is a major headache to maintain and is prone to all kinds of trouble.

## Use case

I want to add more metadata to failing test cases. Specifically, I want to extend `ActionDispatch::SystemTesting::TestHelpers::ScreenshotHelper` from `rails` to pass the screenshot path to the `Minitest::Result` instance for a failing system test case.

This will then allow this information to be used in a reporter.

Tools like GitLab allow embedding a failure screenshot to their test case UI, which is where this can come in handy.

**Comment by zenspider** [comment]
yeah. `Minitest::Result.from` is intentionally restrictive... been poking at this idea and am thinking of adding `@metadata` to `Minitest::Runnable`. It'd be a hash of simple values (read: cleanly serializable) and `from` would copy it over. Then reporters could do what they want with it.

How's that sound?

**Comment by matteeyah** [comment]
@zenspider That would be ideal! For my use case, I only want to pass strings around, so your solution is perfect.

**Comment by zenspider** [comment]
Here's what I'm thinkin': https://gist.github.com/zenspider/490f082c8b5988e3b412de7e559b9548

**Comment by zenspider** [comment]
ugh. go home git diff.... you're drunk

**Comment by zenspider** [comment]
No feedback. Submitted. I'll get a release out shortlyish.

**Comment by zenspider** [comment]
fuck it. released!

**Comment by matteeyah** [comment]
@zenspider So sorry for the long time to reply. This works perfectly!
