### ISSUE TITLE
Make `TestTask.create` adding itself as a `default` task dependency optional

### ISSUE THREAD

**Issue by ParadoxV5** [minitest/minitest#958]
`TestTask.create` builds a variety of Rake tasks and are much appreciated.

However, it is mandartory and un(explicitly )documented that it also modifies the `default` task, which may be undesired if the `default` is for another purpose.

For example, I’m developing a gem that uses a `.gemspec`-registered Rakefile to build (no, it’s not a C extension, which would instead use an `extconf.rb`). I’m not interested to force users to run tests after `gem install`.

**Comment by ParadoxV5** [comment]
(almost 1000 issues/prs, wow.)

I can develop a PR for this #good-first-issue

**Comment by zenspider** [comment]
I think it was an oversight and probably makes more sense removing it, no?

**Comment by ParadoxV5** [comment]
For me, it makes more sense: I *would* explicitly add a `default` task if I’d like `rake` the same as `rake test`.
The PR had compatibility in mind to not switch it off by default. Who knows if folks have been utilizing the default task provided by `TestTask#create`?

**Comment by blowmage** [comment]
Would this be considered a breaking change? Would it make more sense to be made in 6.0?

**Comment by zenspider** [comment]
This isn't API.

**Comment by zenspider** [comment]
This has been removed in 47959978. Thanks for reporting it!
