### ISSUE TITLE
v5.19's removal of MiniTest compatiblity layer broke Mocha

### ISSUE THREAD

**Issue by kyrofa** [minitest/minitest#960]
See https://github.com/freerange/mocha/issues/614 . I appreciate the `MT_COMPAT` environment variable, but that's still an API break, and it broke a number of our projects before we found what was happening. Any reason this wasn't done in a major version bump? Or does minitest not use semantic versioning?

**Comment by zenspider** [comment]
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeXhuZDN4MWJiZzczZjBoeHE3NzRqNG11MXRjM3FocjUyOGpxd3ZhdSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/JDnzNdQVX6K30Ckv6t/giphy.gif)

**Comment by matejzero** [comment]
I'm seeing the same with puppet's beaker tests:

```
An error occurred while loading ./spec/acceptance/class_spec.rb.
Failure/Error: require 'beaker'
NameError:
  uninitialized constant MiniTest
  Did you mean?  Minitest
...
```

**Comment by pgundlupetvenkatesh** [comment]
I got this with Minitest Spec
```
<path>/Ruby32-x64/lib/ruby/gems/3.2.0/gems/minitest-hooks-1.5.0/lib/minitest/hooks/default.rb:3:in `<top (required)>': uninitialized constant MiniTest (NameError)

MiniTest::Spec.register_spec_type(//, Minitest::HooksSpec)
        ^^^^^^
Did you mean?  Minitest
        from <internal:<path>/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:<path>/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
```
Workaround - Downgrading Minitest to v5.18.1 works for now.

**Comment by zenspider** [comment]
"Disingenuous" is titling this issue "removal of MiniTest compatiblity layer".

Mocha has known about the name change [for over a decade](https://github.com/freerange/mocha/pull/156) and yet persists (even after doing a "fix" today) on using the old namespace.

Real fix:

1. Don't use MiniTest.

Legitimate workarounds:

1. `export MT_COMPAT=1`
2. `require "minitest/unit" in your test_helper / whereever.
3. and I suppose pinning back to `5.18.1` if you have some esoteric reason why you can't do any of the others.
