### ISSUE TITLE
undefined method 'context' when running a spec file

### ISSUE THREAD

**Issue by harshwardhanedu** [minitest/minitest#962]
**I am getting this below error when I try to run a spec file**

```
spec/examples/file_name_spec.rb:33:in `block (2 levels) in <main>': undefined method `context' for ClassNamespace:Class (NoMethodError)

 

    context 'context_title' do
    ^^^^^^^
Did you mean?  const_get
        from <ruby_path>/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest/spec.rb:94:in `class_eval'
        from <ruby_path>/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest/spec.rb:94:in `describe'
        from spec/examples/file_name_spec.rb:14:in `block in <main>'
        from <ruby_path>/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest/spec.rb:94:in `class_eval'
        from <ruby_path>/lib/ruby/gems/3.2.0/gems/minitest-5.19.0/lib/minitest/spec.rb:94:in `describe'
        from spec/examples/file_name_spec.rb:5:in `<main>'
        
```
     
**Mentioning the versions in use while getting this issue**

- ruby 3.2.1
- minitest v2.19.0
- minitest-hooks v1.5.1
- minitest-spec-context v0.0.4

**Comment by zenspider** [comment]
This is an issue for https://github.com/ywen/minitest-spec-context/issues/3

But on minitest's side, you can either:

1. Not use minitest-spec-context (you seem to be using it for a single alias from `describe` to `context`)
2. `require "minitest/unit"`
3. set `MT_COMPAT=1` in your shell's environment (or set it in ENV in your rakefile/equiv).

**Comment by zenspider** [comment]
No response. Closing.
