### ISSUE TITLE
MiniTest vs Minitest

### ISSUE THREAD

**Issue by gurgeous** [minitest/minitest#963]
Thanks for all your hard work @zenspider, we love minitest and use it with many projects!

I got bit by this today. It took several hours to track down because my tests were innocently outputting:

`0 runs, 0 assertions, 0 failures, 0 errors, 0 skips`

I had no idea we were using the wrong module name. Sorry about that. A confounding factor is that we were blindly mixing a few methods into `MiniTest::Test`, inadvertently creating an empty module...  I'm not suggesting we go backward, but maybe we could make this fail more violently for laggards like myself? I can imagine a placeholder `MiniTest` that blows up instantly if you try to use it. Just a thought.

Even if we don't make any changes, hopefully this issue will help future googlers. Here are some keywords - tests don't run, no tests found, minitest not running tests, minitest not finding tests, tests are being ignored, tests not loading, no minitest runnables, rake test not running tests, etc...

**Comment by zenspider** [comment]
> I can imagine a placeholder MiniTest that blows up instantly if you try to use it.

How do you envision this?

**Comment by gurgeous** [comment]
Maybe?

```ruby
module MiniTest
  class Test
    def self.inherited(klass)
      # gentle
      warn "`MiniTest` is really ancient and deprecated, use `Minitest` pls"
      # aggressive
      raise "`MiniTest` is really ancient and deprecated, use `Minitest` pls"
    end
  end
end
```

**Comment by AxelTheGerman** [comment]
Thanks for creating this issue - I just upgraded some gems and also had the error `NameError: uninitialized constant MiniTest` which is because somehow `MiniTest::Mock.new` used to work but not anymore.

Using the proper `Minitest` module does the trick - unsurprisingly. Too bad I didn't get the usual Ruby like error messages along the lines of "did you mean 'Minitest'?"

**Comment by epugh** [comment]
This got me, I had `extend MiniTest::Spec::DSL`.  Fortunantly this issue pointed me in the right direction!
