### ISSUE TITLE
[Feature Request] Running single test and single file in most sophisticated way.

### ISSUE THREAD

**Issue by mehmetaydogduu** [minitest/minitest#966]
Issue:
It is hard to run a single test.

Current usage:
```
test 'foo equals bar' do
  assert_equal foo, bar
end
```
`rails test test/system/feature.rb TESTOPTS="--name=foo_equals_bar-v"`

Ideal usage:
```
test.only 'foo equals bar' do
  assert_equal foo, bar
end
```
`rails test test/system/feature.rb`

OR use it like skip
```
test 'foo equals bar' do
  only
  assert_equal foo, bar
end
```
`rails test test/system/feature.rb`

Issue 2: Running single file

Current:  `rails test test/system/feature.rb`
Ideal: 
```
class FooBar < Minitest::Test
  only
end
```

The reasons behind:
The execution command is mostly hardcoded somewhere in IDE settings. It is not quick to change it.

**Comment by zenspider** [comment]
https://github.com/minitest/minitest-focus

**Comment by zenspider** [comment]
No response. Closing.
