### ISSUE TITLE
Test doubles in Minitest

### ISSUE THREAD

**Issue by MatzFan** [minitest/minitest#972]
I've been using your excellent test framework for a while and wondered whether you may ever implement plain old test doubles. Mocking is great where I need to test method calls, but a simple test double which implements the interface of a class I want to isolate from my test class would be useful in situations where I don't need to test calls. AFAIK a `Minitest::Mock` can't be used as plain test double as you can't 'turn off' the expectations functionality. So right now I write stuff like this:-

```ruby
class Double # for KlassNotUnderTest
  def foo; end # interface replicated

  def bar; end
end

class KlassUnderTest < Minitest::Test
  def test_some_method_which_uses_the_klass_not_under_test
     KlassNotUnderTest.stub(:new, Double.new) do
      # isolated test stuff where I don't need to test method calls
    end
  end
end
```

I like Minitest for its simplicity and the intent is clear with the code above. However, the very fact that I have to statically record the interface for KlassNotUnderTest here leads to a dependency which must be maintained if that interface ever changes. It would be nice to be able to do something like this:-

```ruby
class KlassUnderTest < Minitest::Test
  def test_some_method_which_uses_the_klass_not_under_test
     KlassNotUnderTest.stub(:new, Minitest::Double.new(KlassNotUnderTest)) do # pass the class (or module) name so Minitest can dynamically create the interface for a test double
      # isolated test stuff
    end
  end
end
```

I guess `Minitest::Double` would simply be a superclass of `Minitest::Mock` - or maybe the expectation behavior for `Mock` would be added to `Double` via a mixin.

Anyhow there are good reasons for not implementing regular test doubles, not least the fact that properly isolated tests which stub everything not directly under test shouldn't need a double without call expectation behavior. But for imperfect testers like myself the shorthand above would be mighty convenient. TIA.

**Comment by zenspider** [comment]
`obj = Object.new` or `obj = Class.new(CUT).new` along with `def obj.method_override; ...; end` do the job nicely. 

I have no desire to add `Double` to minitest. You're welcome to take a whack at it and publish it as a gem.

**Comment by MatzFan** [comment]
@zenspider understood thanks.
