### ISSUE TITLE
Add option for relative path output of test failures

### ISSUE THREAD

**Issue by Earlopain** [minitest/minitest#974]
I'm developing basically all my ruby applications in docker where the test file locations don't reflect the location on the filesystem.

This results in the file links that aren't clickable in terminals that support that feature. Example:
`FileTest::#original#test_0002_prevents removal once attached [/app/test/model/file_test.rb:18]:`

The real is located at `/home/user/code/project/test/model/file_test.rb`. It would be great if minitest adds a config that allows output of paths relative to another. Relative paths like `test/model/file_test.rb:18` are resolved correctly on the host.

I'm imagining an option like `Minitest.project_root = "/app"` which is simply used to strip the prefix of backtraces.

**Comment by zenspider** [comment]
this is coming... I swear... but the yak is large

**Comment by Earlopain** [comment]
It's all good, I appreciate you wanting to work on this.

For now I'm content with the following workaround in my test helper (in the context of a rails app) to get something similar early.

```rb
module Minitest
  class Assertion
    alias old_location location
    def location
      Pathname.new(old_location).relative_path_from(Rails.root)
    end
  end
end
```

**Comment by zenspider** [comment]
The yak is shaved... I'mma let this bake on my side a tad longer but hopefully will get a release out shortly. Thanks!

**Comment by Earlopain** [comment]
Very cool, thank you!

Would you mind reopening this until you've made the code available? I'd like to get notified when I can try this out.
