### ISSUE TITLE
Raise an exception when no tests are found

### ISSUE THREAD

**Issue by tenderlove** [minitest/minitest#980]
Given a test file like this:

```ruby
require "minitest/autorun"

class FooTest < Minitest::Test
  def test_foo
    assert true
  end
end
```

If I make a typo when trying to run just the single `test_foo` test, Minitest will happily tell me that it ran nothing:

```
$ ruby -I lib thing.rb -n test_foo2
Run options: -n test_foo2 --seed 15906

# Running:



Finished in 0.000304s, 0.0000 runs/s, 0.0000 assertions/s.

0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

If I passed something to `-n`, but nothing ran, then I clearly made a mistake. I think it would be helpful if Minitest raised an exception or printed a "did you mean" style error message rather than running nothing.

**Comment by zenspider** [comment]
the problem is it actually has to run nothing to know that it ran nothing...

**Comment by zenspider** [comment]
done!
