### ISSUE TITLE
Have the changes in the git tag and/or the release on GitHub?

### ISSUE THREAD

**Issue by dorianmarie** [minitest/minitest#981]
What do you think?

I was trying to know what changed between 5.20.0 and 5.21.1

I think this will also get picked up by dependabot

**Comment by dorianmarie** [comment]
Oh I see there is a https://github.com/minitest/minitest/blob/master/History.rdoc also

**Comment by stefannibrasil** [comment]
Oh, thanks for the History link! Yeah, I was confused why dependabot PR did not contain any release notes. I remember it had at some point?

**Comment by zenspider** [comment]
Also if you click on a tag (go to the code page, click releases, go to tags, then click a version) there is a compare dropdown that lets you pick another version and generates urls like so:

https://github.com/minitest/minitest/compare/v5.20.0...v5.21.1

**Comment by zenspider** [comment]
https://rubygems.org/gems/minitest also has "Review Changes"

https://my.diffend.io/gems/minitest/5.21.0/5.21.1

**Comment by stefannibrasil** [comment]
Thanks, @zenspider ! I'm still not sure why, for example, dependabot used to pick up the changelog/commits in the version:

https://github.com/faker-ruby/faker/pull/2804

but on the latest PR, it did not have any of the commit changes: https://github.com/faker-ruby/faker/pull/2888

Maybe this is a bug on dependabot and not here? It's not a big deal, though, just trying to understand :)

**Comment by zenspider** [comment]
Dunno. Try filing a bug on it and see what they come up with.

**Comment by dorianmarie** [comment]
I think putting what's in History.rdoc into the git tags would help, it's much easier to review than reviewing source code diff

(In My Humble Opinion)

Closing this as that's not really a bug, more a For Your Information

**Comment by stefannibrasil** [comment]
> Please refer to this ticket there or link to that ticket here.

Sorry, got busy with other things! I was about to do that when I noticed that dependabot opened a PR correctly this time:

https://github.com/faker-ruby/faker/pull/2894 🤷‍♀️ 

I can see the version changes by clicking on the "compare view" link. I think this was just a glitch because all the other PRs have been opened with the details. I will keep an eye out if it happens again. If it does, I will open the bug report.
