### ISSUE TITLE
skip_all option?

### ISSUE THREAD

**Issue by epugh** [minitest/minitest#983]
I have a set of experimental performance tests written using minitest.  I don't want them to run normally, so I was hoping i could just mark the entire test file with a `skip_all` type command.  The closest I found was https://github.com/ivantsepp/minitest-skip but I don't want to edit the names of all my tests when I go to run them!

I'm curious how others comment out/ignore certain tests?   What is the "minitest" way?

**Comment by zenspider** [comment]
A simple way is to put your performance tests in a separate file and don't load it if you don't want to run it. Or put something like this at the top:
```ruby
return unless ENV["BENCH"]
```

**Comment by zenspider** [comment]
No response. Closing.
