### ISSUE TITLE
No relative test path output if `SyntaxError` is encountered

### ISSUE THREAD

**Issue by Earlopain** [minitest/minitest#984]
The relative output from 5.21 works great. I have noticed a case where output is not relativised:

```rb
# test.rb
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "minitest"
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    require_relative "other"
  end
end

# other.rb
*invalid*syntax*
```

This setup results in the following output:
```
Run options: --seed 22589

# Running:

E

Finished in 0.003831s, 261.0510 runs/s, 0.0000 assertions/s.

  1) Error:
BugTest#test_stuff:
SyntaxError: /home/user/code/test/other_file.rb:1: syntax error, unexpected '*', expecting '='
*invalid*syntax*
        ^

    test.rb:13:in `require_relative'
    test.rb:13:in `test_stuff'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

Not a big issue, I encountered this while upgrading to Ruby 3.3 which contains a bug where valid syntax is currently rejected. I'll just fix that up and the problem goes away but still wanted to report here anyways.

**Comment by zenspider** [comment]
That path is in the exception message itself. I am not touching those in order to preserve their integrity.

> valid syntax is currently rejected

just curious, but show me?

**Comment by Earlopain** [comment]
> That path is in the exception message itself. I am not touching those in order to preserve their integrity.

Eh, fair.

> just curious, but show me?

This one https://bugs.ruby-lang.org/issues/20090. I believe this mostly affects projects that make use of RuboCop with a relativly high minimal version requirement since there's a rule to enforce this notation.
