### ISSUE TITLE
The added "did you mean" output if your `--name` filter matches nothing breaks the Minitest behaviour for multiple runs of the `Minitest.run` method

### ISSUE THREAD

**Issue by ArturT** [minitest/minitest#985]
The added "did you mean" output if your `--name` filter matches nothing breaks the Minitest behaviour for multiple runs of the `Minitest.run` method.

Related to recent changes in Miniest 5.22.0 https://github.com/minitest/minitest/commit/ebb468c81c0eea069234127bd6a101c84e955872

We run Mintest tests in multiple batches. Tests are dynamically allocated to the CI node with the knapsack_pro gem. `::Minitest.run` command is run for each batch of tests.

Minitest shows the `Nothing ran for filter:` error and exits with 1 as exit code (error exit code) when test files returned from the Knapsack Pro Queue API for a given batch include [pending tests](https://github.com/KnapsackPro/rails-app-with-knapsack_pro/blob/63ecba87a0eca6d318f0fd52e274ef27455e5168/test/controllers/pending_controller_test.rb#L10) or an empty [test file with no test cases](https://github.com/KnapsackPro/rails-app-with-knapsack_pro/blob/63ecba87a0eca6d318f0fd52e274ef27455e5168/test/minitest_spec_rails/shared_examples_test.rb#L7).

I reproduced the issue here.

* https://github.com/KnapsackPro/knapsack_pro-ruby/issues/240#issuecomment-1930504221

I expect `0` as an exit code in such a scenario.

Is there a way to disable the "did you mean" behavior for the `::Minitest.run` method? Maybe there should be an option for that?

**Comment by zenspider** [comment]
I just got bit by empty file with no test cases on my work repo... I'm fixing minitest so that nothing ran + no filter == exit 0. But it sounds like you have a filter and you're expecting certain runners to match nothing on purpose? Some sort of rerun failure situation?

**Comment by zenspider** [comment]
OK. I've checked your side of the wall. 

I have a fix in the works that should make the circleci repro pass (no test + no filter == pass)... but it sounds like there are other scenarios where you do have a filter?

**Comment by ArturT** [comment]
How to set a filter? Is --name the only way? I don't recall we use it. 

We just pass arguments from the user to Minitest.run. 

https://github.com/KnapsackPro/knapsack_pro-ruby/blob/master/lib/knapsack_pro/runners/queue/minitest_runner.rb

I will check more when I get home. Thanks.

**Comment by ArturT** [comment]
I tested Minitest 5.22.1. Issue for pending tests is solved but not for an empty test file.

* When I run [`test/controllers/pending_controller_test.rb`](https://github.com/KnapsackPro/rails-app-with-knapsack_pro/blob/7cc2cb52e0e9a50d375a2cdfb134b6d96abccd7c/test/controllers/pending_controller_test.rb#L10) with `::Minitest.run(['--verbose'])` then it returns `true`. That's expected.

* When I run [`test/minitest_spec_rails/shared_examples_test.rb`](https://github.com/KnapsackPro/rails-app-with-knapsack_pro/blob/7cc2cb52e0e9a50d375a2cdfb134b6d96abccd7c/test/minitest_spec_rails/shared_examples_test.rb#L1) with `::Minitest.run(['--verbose'])` then it returns `false`. This is the problem. I expect it to be `true` as it was for Minitest 5.21.2.

[`test/minitest_spec_rails/shared_examples_test.rb`](https://github.com/KnapsackPro/rails-app-with-knapsack_pro/blob/7cc2cb52e0e9a50d375a2cdfb134b6d96abccd7c/test/minitest_spec_rails/shared_examples_test.rb#L1) is an empty test file with no test cases.

Thank you.

**Comment by ArturT** [comment]
The Minitest 5.22.2 version fixed the issue. Thank you.

**Comment by zenspider** [comment]
:heart:
