### ISSUE TITLE
Is 5.22.3 tag missing?

### ISSUE THREAD

**Issue by hsbt** [minitest/minitest#989]
👋 Thank you for your work.

https://github.com/minitest/minitest/releases/tag/v5.22.3 is not found. Is it intentional? `ruby/ruby` repo needs to release tag for testing `minitest` at Ruby CI.

**Comment by zenspider** [comment]
> On Mar 14, 2024, at 20:09, Hiroshi SHIBATA ***@***.***> wrote:
> 👋 Thank you for your work.
> https://github.com/minitest/minitest/releases/tag/v5.22.3 is not found. Is it intentional? ruby/ruby repo needs to release tag for testing minitest at Ruby CI.
> 

Hiiii! Thanks for the heads up! I'm on vacation and apparently released it funny w/o my usual "prepped for release" commit so the new tag wasn't generated and pushed. I've fixed that up and the tag is up now. Sorry!

**Comment by hsbt** [comment]
I confirmed https://github.com/minitest/minitest/releases/tag/v5.22.3 . Thank you.
