### ISSUE TITLE
-Werror mode? - Turn warnings into errors

### ISSUE THREAD

**Issue by casperisfine** [minitest/minitest#990]
A pattern I'm using more and more in the projects I maintain is to turn warnings into errors in the test suite: https://github.com/redis-rb/redis-client/blob/84f1c6567eb02a941e94e8ca41f97d55a026ec4c/test/support/raise_warnings.rb

```ruby
$VERBOSE = true
module RaiseWarnings
  def warn(message, *)
    super
    raise message
  end
  ruby2_keywords :warn if respond_to?(:ruby2_keywords, true)
end
Warning.singleton_class.prepend(RaiseWarnings)
```

I wish this would just be a minitest feature I could enable with an environment variable or something like that.

Would it be something you'd be open to?

Right now I'm working on https://bugs.ruby-lang.org/issues/20205 which will emit a bunch more warning and such feature would make it much easier for me to ensure all of ruby stdlib is warning free.

**Comment by zenspider** [comment]
Man... when I got the mail I read `-Warrior mode` and got really excited! Alas... but maybe we could call it minitest/warrior.rb ??? 🤪

**Comment by ParadoxV5** [comment]
* Resolved by f0f17b9

**Comment by casperisfine** [comment]
Thanks for finishing this, and sorry for dropping the ball, I really didn't get much time to work on it lately 😞

**Comment by zenspider** [comment]
Absolutely no worries! Thanks!
