### ISSUE TITLE
Minitest references Rails in non-Rails code

### ISSUE THREAD

**Issue by soulcutter** [minitest/minitest#996]
Given a file "minitest.rb" that requires minitest/autorun
And minitest 5.22.3 is being used
When I run ruby -Ilib:test ./minitest.rb

I get the output on a failing test:

bin/rails test ./minitest.rb:5

This file does not require any rails, there is no Gemfile, AFAIK nothing that might load any rails thing. bin/rails does not exist at this location. I would expect there be no reference to Rails.

Here's `minitest.rb`
```ruby
require 'minitest/autorun'

class MyTestThatProducesADiff < Minitest::Test

  def test_diff
    assert_equal "Mayonnaise is delicious", "Mayonnaise is delicioous"
  end
end
```

Output
```
$ ruby -Ilib:test ./minitest.rb
Run options: --seed 43692

# Running:

F

Failure:
MyTestThatProducesADiff#test_diff [./minitest.rb:6]:
Expected: "Mayonnaise is delicious"
  Actual: "Mayonnaise is delicioous"


bin/rails test ./minitest.rb:5



Finished in 0.000435s, 2298.8505 runs/s, 2298.8505 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

In case it might be getting polluted from something automatically trying to require rails, here's a filtered list of what gems are present (but not required in my code):

```
$ gem list | grep rails
autoprefixer-rails (10.4.16.0)
dotenv-rails (3.1.0)
factory_bot_rails (6.4.3)
pry-rails (0.3.9)
rails (7.1.3.2)
rails-dom-testing (2.2.0)
rails-html-sanitizer (1.6.0)
rspec-rails (6.1.2)
ruby-lsp-rails (0.3.5, 0.3.3)
sass-rails (6.0.0)
sassc-rails (2.1.2)
sprockets-rails (3.4.2)

**Comment by blowmage** [comment]
Minitest plugin system looks at all installed gems, so its possible you have a plugin installed that is altering the behavior.

Here is what your test looks like in a clean gemset on my system:

```
 >> chruby 3.3.1

 >> ruby -v
ruby 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]

 >> omg clean
Switching gemset to clean

 >> gem install minitest
Fetching minitest-5.22.3.gem
Successfully installed minitest-5.22.3
1 gem installed

 >> echo 'require "minitest/autorun"\n\nclass MyTestThatProducesADiff < Minitest::Test\n\n  def test_diff\n    assert_equal "Mayonnaise is delicious", "Mayonnaise is delicioous"\n  end\nend' > clean_test.rb
 
 >> cat clean_test.rb
require "minitest/autorun"

class MyTestThatProducesADiff < Minitest::Test

  def test_diff
    assert_equal "Mayonnaise is delicious", "Mayonnaise is delicioous"
  end
end

 >> ruby ./clean_test.rb
Run options: --seed 59813

# Running:

F

Finished in 0.000258s, 3875.9690 runs/s, 3875.9690 assertions/s.

  1) Failure:
MyTestThatProducesADiff#test_diff [./clean_test.rb:6]:
Expected: "Mayonnaise is delicious"
  Actual: "Mayonnaise is delicioous"

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by stringsn88keys** [comment]
I've spent several hours doubting my sanity because `active_support` is getting loaded into a project's tests... for a project that has no non-default gems (only a source line in the `Gemfile` at this point). 

I feel like there's enough confusion over Ruby vs. Rails extensions to ruby without `minitest` loading `active_support` via the `rails_plugin` just because the developer has installed a version of Rails without https://github.com/rails/rails/pull/51718
