### ISSUE TITLE
How do I define asserting helpers?

### ISSUE THREAD

**Issue by Nakilon** [minitest/minitest#998]
I use minitest with spec syntax.
I have a complex stubbing method that invokes such methods as `assert_equal`, `assert_operator`, etc. I want to reuse it in another tests file so I need to put it in some common place to require, but usual `def` elsewhere will not find those assertion methods. What is the way/place to define the asserting helpers at? Maybe some Minitest class that I have to extend?

**Comment by zenspider** [comment]
Such a pain, no? Always bites me. 2 easy (cheat?) ways I know of... go ahead and shove it in Minitest::Test (or Spec) or include Minitest::Assertions in your module.

If it is app/lib specific, then I usually put em in a Test/Spec subclass of their own that I subclass from. For specs you can "register" this new spec type:

```ruby
  Minitest::Spec.register_spec_type(/XTest$/, MyCustomTest)
# or
  Minitest::Spec.register_spec_type(MyCustomTest) do |desc|
    desc.superclass.is_a? Something # or whatever
  end
```

**Comment by zenspider** [comment]
Please close if your questions have been adequately addressed.
